### ISSUE TITLE
area of polygon ...

### ISSUE THREAD

**Issue by mrlhayes** [ankitrohatgi/WebPlotDigitizer#102]
just to say an excellent tool I use a lot
could you extend to calculate area of closed polygon sets ?
the math is here ..
http://www.mathopenref.com/coordpolygonarea.html

I do it by exporting x y pairs to excel but a bit inefficient ...

**Comment by ankitrohatgi** [comment]
Thanks! This has been on my wish list for a while. I'm hoping to get this in soon.

**Comment by ankitrohatgi** [comment]
This has been added in the latest release.
