### ISSUE TITLE
Old beta version

### ISSUE THREAD

**Issue by StefRe** [ankitrohatgi/WebPlotDigitizer#106]
Google search shows a beta version at a rather prominent place:
![webplotdigitizer-google_search_result](https://user-images.githubusercontent.com/19879328/30771904-d761d11a-a051-11e7-93ea-c122d2fc2710.png)
This still refers to version 3.11 whereas the main version is already 3.12.

**Comment by ankitrohatgi** [comment]
Google search is weird - it doesn't show that for me, even if I go incognito and search. I have deleted the "beta" on the server now as it doesn't serve any purpose anymore.
