### ISSUE TITLE
Tree widget not visible in Internet Explorer

### ISSUE THREAD

**Issue by StefRe** [ankitrohatgi/WebPlotDigitizer#111]
Internet Explorer version 11.0.9600.18792 --> missing tree widget:
![ie](https://user-images.githubusercontent.com/19879328/30964169-83caf38a-a450-11e7-9716-2b2ec66b3d53.PNG)

Firefox 55.0.3 --> OK:
![ff](https://user-images.githubusercontent.com/19879328/30964281-f9a85dcc-a450-11e7-8a6f-f3820340c34e.PNG)

(current develpment snapshot, Windows 7)

**Comment by ankitrohatgi** [comment]
Not really planning to support I.E. going forward. Also I'm making a lot of changes in the master branch so some bugs are expected. I fix these type of issues before "release".
