### ISSUE TITLE
Unable to import JSON file in new version

### ISSUE THREAD

**Issue by aranci** [ankitrohatgi/WebPlotDigitizer#115]
Hi,
I'm having trouble importing JSON files in Wpd since the last update. I created a new json file in the new version, but the same file won't import in the new version at all. The json contains calibration points for a polar diagram (center, point 1 and 2) which in the earlier version I could use repeatedly.

**Comment by ankitrohatgi** [comment]
Hello,
Can you attach here or email me the JSON file? The new version should be able to read older files. If it is not, then there's probably a bug somewhere that I can fix.

In the meantime, you can use the old version till this is fixed: http://arohatgi.info/WebPlotDigitizer/app3_12/

Thanks

**Comment by aranci** [comment]
[wpd_project.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/1438857/wpd_project.zip)

Here is the new json file I created moments ago. It won't import in the new version.
Meanwhile, I've used the old version and created a new json file there and imported it in the old version again- it worked. Now it seems the only problem is in the new version...

**Comment by ankitrohatgi** [comment]
Thanks, I'll fix the new version soon.

**Comment by ankitrohatgi** [comment]
The JSON loads for me in the new version. How are you establishing that the import in the new version does not work? If you move the mouse around after import, do the (r, theta) values under the zoom view match?

**Comment by aranci** [comment]
First thing I do is import the image. After that I choose the polar diagram and select the center, point 1 and 2. After that I adjust the R and theta for the points. I export the json, so I could use it again for a different diagram. The image is always 500x500. Then, after I try to import the json I need in Chrome, nothing happens. I should receive the pop-up "JSON loaded", but it is like I didn't do anything. I tried in Microsoft Edge and the only thing that shows up is "processing" in the top, but no datasets or axes calibrations are loaded.

**Comment by ankitrohatgi** [comment]
Are you sure you’re using “load project” in the file menu and not “load image”?

**Comment by ankitrohatgi** [comment]
JSON is not an image

**Comment by aranci** [comment]
I'm using load project each time.

**Comment by ankitrohatgi** [comment]
Aah - I just managed to reproduce the problem on Windows. Looks like on Windows the file type is not detected properly :( It seems chrome on Linux or Mac behaves a little differently. 

This should be an easy fix, I'll fix this tonight. Sorry about the trouble and thanks for reporting this.

**Comment by ankitrohatgi** [comment]
btw, this works on Firefox on Windows, but Chrome and Edge have some weird issue going on.

**Comment by aranci** [comment]
Awesome! thanks for your help.

**Comment by ankitrohatgi** [comment]
This should be fixed now. If you are using Chrome, then I recommend reloading the app with Ctrl+F5 to force any cached code to be reset for this page.
