### ISSUE TITLE
Color Foreground Color under Automatic Extraction does not work anymore

### ISSUE THREAD

**Issue by Nodragem** [ankitrohatgi/WebPlotDigitizer#126]
Hello,
Thank you very much for this fantastic piece of software, it saves me a lot of time as a computational modeller.

Here how looks my data extraction project:
![image](https://user-images.githubusercontent.com/10520249/34667872-ca74afe4-f462-11e7-9ed9-a33942b25d50.png)

After I closed and opened my project again, I was unable to change the color of the automatic extraction anymore (defaut blue foreground). That totally messes up my progress of this project obviously :) 

If I create a new project, I can change the color, if I re-opened the above project, I can't.

Hope there is a solution...

**Comment by ankitrohatgi** [comment]
Hello, this was pointed out by someone else as well and I have fixed in the development code here as part of issue #125. I just need to update the released code on the website and rebuild the desktop apps.

**Comment by ankitrohatgi** [comment]
The website version and the desktop apps have now been updated and should contain the fix (version 4.1)
