### ISSUE TITLE
Chrome. Panel with downloaded files disturbs observation of acquire data.

### ISSUE THREAD

**Issue by xanfus** [ankitrohatgi/WebPlotDigitizer#135]
While panel with downloaded files below the page is present, view on acquire data is obstructed. Close panel to restore view.
![image](https://user-images.githubusercontent.com/5682375/36096954-b9503f5e-1009-11e8-8bb1-1d2d56b0f6f4.png)

**Comment by ankitrohatgi** [comment]
Hello, what OS is this on? I am unable to reproduce this behavior. Also are you sure the graphics drivers etc. are all good on your machine? If that's all good, then can you see if there are any errors in your inspector console (Right click->Inspect->Hit the "Console" tab)?

**Comment by xanfus** [comment]
Ubuntu 16.04.3 x64. Ivybridge accelerator is recognized. More on console tomorrow.

**Comment by xanfus** [comment]
Erroneous behavior is no longer present.
