### ISSUE TITLE
Feature request : log2 support for XY axis

### ISSUE THREAD

**Issue by AndySouth** [ankitrohatgi/WebPlotDigitizer#136]
Firstly to say the software is excellent and super user-friendly, thankyou.

However I have a plot with a log2 based axis. Could the axis callibration support log2 as well as log10 ?

Thanks,
Andy

**Comment by ankitrohatgi** [comment]
Hello, the axes scaling math is base-independent, but I haven't tested the entire process out thoroughly with anything other than base 10. I think I just need to test this out properly and fix minor stuff if necessary. I'll try to add that in the next update.

**Comment by ankitrohatgi** [comment]
I tested my axes calibration code with base 2 values and everything looks good as-is. The only thing that won't work as expected is the X Step with interpolation algorithm which was fixed recently (#134) and will work in the next release.

Just make sure that when you enter calibration values, you enter the numbers without the exponents, e.g. for 2^4, type in 16.

**Comment by AndySouth** [comment]
Super, thanks for looking into this for me.
I found that my problem was due to an incorrectly copied axis in a later publication, when I found the original webplotdigitizer worked perfectly.
