### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by ruelcedeno** [ankitrohatgi/WebPlotDigitizer#138]
Hello Sir. Here's my proposal for a new logo for the website. Please let me know what you think. 

https://steemit.com/utopian-io/@ruel.cedeno/proposed-logo-for-webplot-digitizer

**Comment by ankitrohatgi** [comment]
Hello Ruel,

Thanks for sharing this, the icon is fantastic! This definitely captures the intent of the tool very well. If you permit, I can switch to using this this weekend. I was going to put together a public list of contributors and would be happy to give you the credit for this part.

Thanks,
Ankit

**Comment by ruelcedeno** [comment]
Thank you so much! Glad you like it! It's an honor!

**Comment by ankitrohatgi** [comment]
Hello Ruel, I have included your icon in my recent commit (f742118ab91b6847b333d67b187da0fe3a07c487), but it will take me a few days before the website etc. is updated.
