### ISSUE TITLE
Exporting data issue

### ISSUE THREAD

**Issue by Vicente451** [ankitrohatgi/WebPlotDigitizer#140]
I was able to successfully digitize my X-Y plot.
The problem was, upon exporting I was only able to get part of the digitized data.
That part being the data that originally fell between the X1 & X2 points specified.
The actual range of the X-axis started before X1 and went past X2.
Let me call those points X0 and X3.  Using the Automatic X-Step algorithm, 
I specified my X0 and X3 points as the range to
digitize under settings, and got that data digitized (visually).
But upon exporting/saving, I only got the data between X1 & X2.
On my particular job the values for X were as follows:
X0 = 1
X1 = 30
X2 = 335
X3 = 365
I just noticed that it looks like the original data that should have been scaled between 30 & 335 got rescaled to 1 and 365. That is a problem!

**Comment by ankitrohatgi** [comment]
I see that you have two calibrations here [XY and XY2]. Did you mean to switch the calibration for the dataset to XY2 (click on Default Dataset, change the option in the dropdown on the left where it says Axes: [XY])?

If you want to do two separate calibrations on this image and keep both results, then you should create another dataset and set the axes of the second one to the second axes.

**Comment by Vicente451** [comment]
I did not realize I had two calibrations - and that were possibly conflicting with each other.
I deleted 1 and reran the dataset and got reasonable results, so I think this took care of the problem.
Thanks

**Comment by ankitrohatgi** [comment]
That's great. I'll close this issue.
