### ISSUE TITLE
Feature Request: Allow User Override of the x- or y- Value

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#142]
As I was recently working with another figure like the one in #74, I thought of a simplification that I often need that would get very close to the feature requested there, but is a bit more general.

Sometimes when working with a figure, I know the x- or y- value because, for instance, it is from a restricted set of values (like 57, 71, 85, ... for the x-axis in #74).  It would be helpful to be able to override the extracted value.

One idea for how to implement this is that in the "View Data" window, what is currently in the "digitizedDataTable" textarea could be converted to an html table with both the original value and a textarea for overriding the original value.  Blank in the new textarea could be no override and any value would be an override.  (Ideally, the override value could be any character string-- not just a number.  That would work well for "EOS" in the figure in #74.)

In the .csv and .json output, if there were no overrides, the output would be as is currently exported.  If there were an override, then there could be a new column like x_original and y_original with the unmodified values and the x and y columns would show the overridden values.

**Comment by ankitrohatgi** [comment]
I run into this too and I was thinking of adding something to allow this. I'll try to include something soon. Thanks for your suggestion!

**Comment by billdenney** [comment]
As I'm thinking about this more, I can imagine that this would take 2 forms:

1. Only modify the interpolated value leaving the pixel location alone.
2. Modify both the interpolated value and the pixel location.

I think that both of these should force the interpolated value to be whatever the user indicates (ideally as a character string to allow for it to be fully generalized (such as the "EOS" in the figure for #74) and to prevent floating point error in the interpolation from coming back through.

Ideally, this would be possible on a group of points at the same time with some form of area selection.  That way, we could implicitly implement #74 without specific code for that type of figure.  (The general case is almost always better than the specific case! :) )

**Comment by billdenney** [comment]
One more thought is that it would be useful to have one more feature here:  Align a set of points vertically or horizontally.  Sometimes I don't know what the absolute value should be, but I know that all the points should be at the same x- or y-value.  Alignment to the median (or mean) of the values would help simplify post-extraction analysis.  This alignment would be especially helpful in combination with error bar extraction (#71).

**Comment by billdenney** [comment]
This was fixed in #211.
