### ISSUE TITLE
bad automatic extraction

### ISSUE THREAD

**Issue by springboksoct** [ankitrohatgi/WebPlotDigitizer#149]
However i try to use the automatic settings the automatic data extraction gets confused,   it would be good to have an option for dY or a way of eliminating the grid

![sct3160kl eoneoff _vds](https://user-images.githubusercontent.com/41568424/43064928-9800460c-8e60-11e8-9db4-38c0360a57b0.PNG)
![image](https://user-images.githubusercontent.com/41568424/43064953-a8f93b8a-8e60-11e8-884a-799690c70796.png)

**Comment by ankitrohatgi** [comment]
Hey, there are a couple of things you can do in this instance:

1) Try grid removal (click on "Axes" on the left side and you'll see a "Remove Grid" option in the lower left). There's some info here: https://automeris.io/WebPlotDigitizer/blog/posts/grid_removal.html

2) Alternatively, you can try using the "Pen" tool when drawing the mask and pick a very narrow width when painting over the line.
