### ISSUE TITLE
Cannot see the pen highlight when loading the previously saved project

### ISSUE THREAD

**Issue by rahulsp07** [ankitrohatgi/WebPlotDigitizer#159]
The software is awesome and time saving. The issue i am facing now is that once i have saved a paricualar project and again open the project, neither i can see the pen highlight on the curve nor i can plot more or less points using automatic extraction( if i decrease/increase the delta points, the points gets disoriented in some different manner). What is the remedy for this? (PS: i have changed the foreground colour to black)
![tm](https://user-images.githubusercontent.com/47629215/52781072-afc6f480-3071-11e9-8fee-75b146e68dd8.png)
![tm1](https://user-images.githubusercontent.com/47629215/52781082-b3f31200-3071-11e9-902b-74912492d85a.png)

**Comment by ankitrohatgi** [comment]
The current released version did not save the masks along with the project data, so you have to setup automatic extraction algo from scratch like you did the first time. Just redraw the mask like you did when the plot was digitized first. I have addressed this shortcoming in the code that's under development right now. The masks and all the algo settings will be saved and restored in the next version.

**Comment by rahulsp07** [comment]
ok sir and hats off for creating such good software.
