### ISSUE TITLE
Wrong Translation: Logarithm

### ISSUE THREAD

**Issue by Biggi987** [ankitrohatgi/WebPlotDigitizer#161]
Hello, 
you have a translation mistake in the german version. After marking the points at the axes and setting the values for the points in the english version you can choose if the axis are logarithmical. In german it says: 'Auflösung des Protokolls' which doesn't mean anything close to logarithms. Just replace it with 'logarithmisch' and everybody will understand it. 

Best regards
Biggi
![webdigi](https://user-images.githubusercontent.com/47886371/53235482-342cff00-3692-11e9-8bfa-1b8a96ae3067.PNG)

**Comment by ankitrohatgi** [comment]
Thanks! I have made this change for the future version.
