### ISSUE TITLE
Solution to start up .png

### ISSUE THREAD

**Issue by jackjameshoward** [ankitrohatgi/WebPlotDigitizer#162]
Can I have the solution/equations for the startup.png so I can see how well webplotdigitizer work's?
I've captured the data from that png and I have tried to recreate the plot, using that image as a standard benchmark. I'd like to see how well I've done recreating it.
Thank you.
![start](https://user-images.githubusercontent.com/4273996/54588977-54937380-4a1c-11e9-8c6a-51bf9171a7ea.png)

**Comment by ankitrohatgi** [comment]
```
# Python script to generate the default plot

import numpy as np
import matplotlib.pyplot as plt

# Create an array of 100 linearly-spaced points from 0 to 2*pi
x = np.linspace(0,2*np.pi,1000)
y = np.sin(6*x)*np.power(x,1.5)/10.0

x2 = x
y2 = np.power(x, 1.5)/10.0 + 0.1

x3 = x
y3 = -np.power(x, 1.5)/10.0 - 0.1

# Create the plot
plt.plot(x,y,'b')
plt.plot(x2,y2,'g')
plt.plot(x3,y3,'r')
plt.plot(x,-y,'orange')

plt.xlim([0, 2*np.pi])
plt.ylim([-2.0, 2.0])
plt.xlabel('x')
plt.ylabel('y')

# Save the figure in a separate file
plt.savefig('start.png')

# Draw the plot to the screen
plt.show()
```

**Comment by ankitrohatgi** [comment]
There better ways to test things btw, but since you asked here it is :)
