### ISSUE TITLE
Extracting data for one color of a multi-plot, multi-color graph extracts data for multiple colors

### ISSUE THREAD

**Issue by GuyMZ** [ankitrohatgi/WebPlotDigitizer#163]
I have an anti-aliased graph conataining black, red, blue, and green plot lines. I am interested in extracting data from only the red plot. I sample the color of the line as "foreground color." When I run the extraction, program extracts data points for the red plot AND the black plot, axes, and axis values. If I select any of the other colors as foreground color, different combinations of extractions from ALL colored plot lines results. Seems this feature isn't working at all. If I set the foreground 
color to red and then draw a box around the red plot, I get data only for the red plot.  If I use the pen to enclose the red plot, that doesn't work either -- only a few points are extracted.

**Comment by ankitrohatgi** [comment]
The tool is working fine for me (and many others). What distance value are you using? Also if you press "Filter Colors" you should see the color range the algorithm is going to use. If you are convinced there's an error, then please share the project file (.tar as it contains the image as well).
