### ISSUE TITLE
automatic bar extraction not working ?

### ISSUE THREAD

**Issue by ricorico94** [ankitrohatgi/WebPlotDigitizer#164]
I tried to understand how automatic bar extraction works, but it failed every time. I read the documentation but still didn't make it working. I tried to find video tutorials, but no luck for automated extraction on Bar.
I used for instance this bar chart:
![picture0test2b](https://user-images.githubusercontent.com/25903167/56297713-272c0980-6131-11e9-9efc-377268bfefff.jpg)
I clicked on the Box and dragged a box englobing all bars. I selected the yellow (from color picker) as foreground, then clicked the "filter color" button: at tat point, I see the tool found properly the bars.
Then I click on run.. and almost nothing happens. On the left, I can now read "data points: 431".. (obviously not matching the numbe rof bars of the graph) and if I "view Data", I see a number of of rows, but all with a number and "NaN" as value. Nothing appearing on the picture (no data point, nothing).
What do I do wrong ?
Could be a great tool otherwise (but handling only fully manual is a bit tideous).

**Comment by ankitrohatgi** [comment]
This seems like a bug. I will investigate. Thanks for pointing this out.

**Comment by ankitrohatgi** [comment]
I have found the source of the bug, but it looks like I also need to add some tests to cover this part to prevent future breakage. If you want I can share a desktop version to you, but I am hoping to have the online version fixed by this weekend.

**Comment by ankitrohatgi** [comment]
I went ahead and updated the online version with the fix. Please try it again.
