### ISSUE TITLE
Bug? Data extracted with "same" result

### ISSUE THREAD

**Issue by cinantya** [ankitrohatgi/WebPlotDigitizer#166]
Hi, I've searched the past issues and current open issues, but seems that nobody discussed about this.

Background:
I am extracting simple graphs (mostly bar chart) to collect the Means and SD. As I need both number, I did that manually by Bar plot and use different ticks for Means and max SD of each data entry. So far I did around 100+ graphs already. After extracting the data, I download as CSV, move the data into an excel file and obtaining the SD value by subtracting Means from max SD values. When I don't have max SD visible, I use min SD and using absolute formula in excel to obtain positive SD. 

What I found:
When I work with multiple entry in 1 graph, I found the SD values to be the same. Initially, I give it the doubt that how I put the markings may be the same. But as it keeps on repeating, I redo some of the graphs. To my surprise, the data sort of changed. Example below:

[Treatment 1, 2, 3, 4, 5]
1st Run: Means [48.96226415, 37.35849057, 50.37735849, 95.94339623, 91.13207547]
1st Run: Max SD [60.8490566, 49.24528302, 62.54716981, 107.5471698, 103.0188679 ]
1st Run: Calculated SD [**11.88679**, **11.88679**, 12.16981, 11.60377, **11.88679**]

> So looking at the first run, the same value of calculated SD shown on Treatment 1, 2 and 5.

2nd Run: Means [49.47189, 37.41056, 50.49404, 96.08177, 91.17547]
2nd Run: Max SD [60.91993, 49.47189, 62.55537, 107.7342, 103.2368]
2nd Run: Calculated SD [11.44804, **12.06133**, **12.06133**, 11.65247, **12.06133**]

> Looking at the second Run, same values of SD found on treatment 2, 3 and 5. 
>> Variation between Means and Max SD reading on both Runs is considered as variation on eye sight and hand coordination. 

Figure that I used, along with the project file (*.json) and CSV downloaded are zipped and attached. 

Let me know if this is an issue, as I found this pattern on multiple data extraction.

Thank you. 

[1906 Fig 2 Issue.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/3159994/1906.Fig.2.Issue.zip)

**Comment by ankitrohatgi** [comment]
This is not a bug, and I think I can explain the patterns that you see:

If you use the keyboard arrows to adjust the points, each button press moves the data point by one pixel on the screen. For this image, the default zoom will be around 2x (depends on your window size as well) and I measured that 0-120 range is covered by ~300px. So if you leave the zoom at whatever default value is and use your keyboard to fine tune the location of the data points, then each button press will move the point by 1px which is equivalent to approx 120/300/2 = 0.2 in y-axis units. This is very close to the difference between your runs (12.06-11.88) = 0.18 units. If you leave the zoom level to default, then your resolution is limited to ~0.2 units which explains why you get same exact value sometimes.

If you want better accuracy than this, or want to verify the above, then just zoom in the image using the [+] icon on the top right and adjust data points in that view. This will reduce the distance covered by 1px on the screen in term of y-axis units.

Hope this helps!

**Comment by cinantya** [comment]
Thanks! I'll try it.
