### ISSUE TITLE
Problem detecting color around the formula: R=200, G=200, B=0 

### ISSUE THREAD

**Issue by auo355** [ankitrohatgi/WebPlotDigitizer#167]
Problem detecting color around the formula: R=200, G=200, B=0

**Comment by auo355** [comment]
![Cannot pick out the colour](https://user-images.githubusercontent.com/28743771/57749741-f2708b00-76b9-11e9-91d9-377a30e600b3.png)

**Comment by auo355** [comment]
could not detect the above colour

**Comment by ankitrohatgi** [comment]
works fine for me... did you draw any mask?

**Comment by auo355** [comment]
Thanks, it worked this morning.

kind regards
