### ISSUE TITLE
Suggest adding bibtex item on wesite to make citation easier

### ISSUE THREAD

**Issue by syrte** [ankitrohatgi/WebPlotDigitizer#169]
I'd like to cite Webplotdigitizer in my paper. It would make citation much easier for BibTeX users if you can also make a BibTeX item on the page https://automeris.io/WebPlotDigitizer/citation.html 

e.g. something like below
```
@misc{Rohatgi2019,
  url = {https://automeris.io/WebPlotDigitizer},
  author = {Rohatgi,  Ankit},
  title = {Webplotdigitizer: Version 4.2},
  year = {2019}
}
```

Or you can submit your document to the arxiv website, then we can simply cite the document as normal papers.

Just a suggestion, feel free to ignore.

**Comment by ankitrohatgi** [comment]
Hey, thanks for the tip! I’ll add it later today :)

**Comment by ankitrohatgi** [comment]
done 👍
