### ISSUE TITLE
Feature Request: Persistent Identifiers

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#171]
I have some use cases where I will extract data from a scientific journal article, and maybe for the first pass, I'm only interested in some of the data.  I later can come back and extract more data in the same file (perhaps even from the same graph).

After each of these passes, I may need to modify the underlying data, for example to correct known errors in the data (that may only be obvious from data outside the graph, and I'm a purist who likes to have original source information just as it is in the source).

It would be helpful to have a persistent identifier for the axis, dataset, and point so that were features like axis or dataset name modified or additional axes or datasets were added, the identifier would stay the same.  I would think it would be a sequential integer within the file, and (related to #168) a data point could be identified by all of:

* Page number
* Axis number
* Dataset number
* Point number

If a value were deleted, its value would not be replaced, but if a value were modified, its value would be maintained.  With that, the identifiers would not necessarily be sequential within a set, if for example, you add a point to dataset 1 and then add a point to dataset 2, they may be point ID 1 and point ID 2. Then point ID 2 would never exist within dataset 1.

**Comment by billdenney** [comment]
For simplicity, perhaps these identifiers would apply to any new object (axis, dataset, and point).  And, since they would be arbitrary (presumably integers), there could simply be a "next ID number" stored in the JSON header such that the next object gets that value and increments the "next ID number" counter.

With that said, in the future, I'd like to be able to merge two WPD JSON files together, so ideally the identifier could be an arbitrary string so that the merge of files (which would occur external to WPD) could reassign the ID values to something like "A-1" and "B-1" to separate values that started in the first or second files.

**Comment by ankitrohatgi** [comment]
[UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) is what is typically used for this purpose.

Since this is an HTML5 app, generating and storing IDs per data point will hurt performance in quite a significant manner.

**Comment by billdenney** [comment]
Thanks for the pointer to UUIDs; I agree that they would make sense.  I don't understand how this would significantly hurt performance.  With the below, I'm not trying to change your mind, but I'm trying to understand.

I'm just missing something, I think.  I just found a UUID generator for JavaScript (https://github.com/kelektiv/node-uuid) that can generate >1M UUIDs with version 1 per second (and I found that benchmark due to one of those rabbit holes that I can go down when looking into something new: https://jsperf.com/node-uuid-performance/63).

And, it seems like adding a UUID at every initial point creation would be minimally invasive then storing that value with the raw x- and y- pixel values would cover the persistent identifier need.  If the raw x- and y- pixel values were modified, it would not change, and if the point were deleted, it would go away.

**Comment by ShelbiL** [comment]
Hi Ankit,

I think I am asking for the same thing for very different reasons.  I am interested in at the least labeling the plot points on the image.  Simply having (x,y) next to the point would do. I wouldn't need them to be saved at this time because if they were on the screen I could just take a screenshot.

I would like to use WPD in my creation of custom stitches on a sewing machine.  The built-in software on the machine uses a 2D x,y  graph which must be manually input after you work it all out on paper.  While WPD would speed up the process of extracting the points, it appears that the points are listed left to right.  The machine/custom stitch can ostensibly move backward. Therefore, a point on the left can come after a point on the right.

**Comment by billdenney** [comment]
For my use case, I think that #242 will close this.
