### ISSUE TITLE
Documentation Request: How to host WebPlotDigitizer on a different server

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#177]
I hope that this is a simple one.  Can you please add documentation of how to serve WebPlotDigitizer from a different server than the included go server?  The instructions could perhaps as simple as "build the html" then "serve the /app directory".  I assume that the instructions would either go into the developer guidelines or the readme for the webserver directory (or even better, they go into one of those and the other points to the full instructions).

This is not a request for all the permutations of how to set it up on every different server type (e.g. how to do it on apache, nginx, IIS, ...), but just a generic bit of info on what is required to host differently than the default go.

Are there requirements of fixed directory names (i.e. can it be served out of a "http://www.example.com/WebPlotDigitizer" subdirectory or a generic subdirectory)?  If it can't be served out of a subdirectory today, could a patch be made to make all paths relative so that it could be served from any subdirectory on any server?  (Which would extend this beyond a documentation request. :) )

**Comment by ankitrohatgi** [comment]
As you guessed, if you just build the html and serve `/app` folder, everything works. Due to limited bandwidth, I do not want to officially support this method or want to guarantee that it'll keep working in the future.

**Comment by billdenney** [comment]
That makes sense.  Thanks for the confirmation.
