### ISSUE TITLE
Cross hair for fine tuning does not work on Mac

### ISSUE THREAD

**Issue by Olsthoorn** [ankitrohatgi/WebPlotDigitizer#183]
It seems that the fine-tuning cross hair for axis calibration does not react to navigation keys on Mac (Mac High Sierra vs 10.13.6). There is no reaction to the keyboard navigation keys, not with pressing the fn key nor without pressing the fn key. Including shift, control, option or command also yield no reaction to the cross hair fine-turne cursor in the window to calibrate axes.

**Comment by AJamesPhillips** [comment]
Works fine for me on Chrome.  Remember you need to *first* click to place a point, and only then can you use the arrow keys to fine turn it's position.

**Comment by ankitrohatgi** [comment]
agree with @AJamesPhillips  above.
