### ISSUE TITLE
Troubles while using WebPlotDigitizer with nodejs: file reference_project.json not found. 

### ISSUE THREAD

**Issue by rodricfanou** [ankitrohatgi/WebPlotDigitizer#184]
Dear authors, thanks for this useful tool. I have tried using it with a script to fetch data from thousands of images and thus with nodejs. As suggested in the readme, I changed the path to the "wpd_node.js" file, after downloading the npm package. I get the following error when trying to run the script "node_examples/batch_process.js". 

./batch_process_images
Reading: ternaryreverse.png
{ Error: ENOENT: no such file or directory, open './reference_project.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at digitizeImage (/.../WebPlotDigitizer/node_examples/batch_process.js:34:44)
    at jimp.read.then.img (/.../WebPlotDigitizer/node_examples/batch_process.js:84:69)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './reference_project.json' }
{ Error: ENOENT: no such file or directory, open './reference_project.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at digitizeImage (/.../WebPlotDigitizer/node_examples/batch_process.js:34:44)
    at jimp.read.then.img (/.../WebPlotDigitizer/node_examples/batch_process.js:84:69)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './reference_project.json' }

It highlights the absence of a file reference_project.json. Can anyone who had this issue before/the authors give me any indication to fix this issue or push the said file to the repo, etc ?
Thanks in advance

**Comment by ankitrohatgi** [comment]
You should provide a `reference_project.json` as an input. This is some project json containing axes calibration etc. that you intend to use. The examples are meant to be read and modified to your use case.

**Comment by rodricfanou** [comment]
Thanks for your quick reply and your feedback. We tried to use the tool through the web and got the data under a format which we believe is that of reference_format.json. I will create another ticket and continue my questions there (because we then bump into another issue).

**Comment by rodricfanou** [comment]
Do you have any template of the reference_format.json that would work with the *.js in the repository?
