### ISSUE TITLE
Specify plot color

### ISSUE THREAD

**Issue by fsfuji** [ankitrohatgi/WebPlotDigitizer#187]
The problem I am having is with the scanned plot the colors are not uniform. I pick a color but have to pick the correct hue.  With the mouse it takes some time to move it precisely. This can be accomplished quickly if I could use the keyboard keys to fine tune the position of the color picker.

**Comment by nbehrnd** [comment]
Hello fsfuji,

I assume your file is an x-y-plot.  In the panel of «automatic
extraction», just below the toggle of foreground color / background
color, you find the entry of distance.  The larger this number, the
more tolerant webplotdigitizer is to recognize e.g., a turquoise as a
blue.  This adjustment is independent of (but may be quite boosted by)
using the box and the pen-tool, too around 9 minutes in Ankit's
presentation on Plotcon2017.[1]  Does this help you?


[1] The video is right below the presentation of the program
itself, https://automeris.io/WebPlotDigitizer/

**Comment by ankitrohatgi** [comment]
Thanks @nbehrnd 

I'd also like to add that you can also zoom-in if you want to select something from a very specific region.
