### ISSUE TITLE
Cannot get image to calibrate properly...

### ISSUE THREAD

**Issue by awa5114** [ankitrohatgi/WebPlotDigitizer#189]
Hi there. I'd like to digitize the image attached below. However it seems impossible to get the cross-hairs to be centered on the top left corner of the plot.
![exams_summarized_1](https://user-images.githubusercontent.com/24267968/71614723-c3a61700-2bad-11ea-88dc-269fe98070c2.jpg)

I have tried to:
 - resample this to finer resolutions
 - increase the magnification size in the "Magnified view settings"

However I cannot get the cross-hairs to center on the top left corner. Help please? Thanks.

**Comment by nbehrnd** [comment]
In my experience with x-y-plots and the digitizer, it sufficies if the indicators x<sub>1</sub> and x<sub>2</sub> are set _well enough_ along x (and the y<sub>1</sub> and y<sub>2</sub> _well enough_ along y) with some adjustment by the the arrow keys.  There is no need that one or two coincide with the coordinate system, nor that an indicator for x is equally accurately set for y.  It is well suitable to define x<sub>1</sub> and x<sub>2</sub> at the grid's intersection (2,3) and (20,3) / (conusweerstand, diepte) inferred from the axes, as in the examples below.

(Truncate the .txt, then re-open the projected .tar with WebPlotDigitizer.  You see the reference points again after clicking on axes ->xy -> tweak calibration. Two account for two left-to-right abscissae, there are two example files, obviously omitting the third one.)

[wpd_project_wrijvingsweerstand.tar.txt](https://github.com/ankitrohatgi/WebPlotDigitizer/files/4012736/wpd_project_wrijvingsweerstand.tar.txt)
[wpd_project_conusweerstand.tar.txt](https://github.com/ankitrohatgi/WebPlotDigitizer/files/4012737/wpd_project_conusweerstand.tar.txt)

**Comment by awa5114** [comment]
What actually ended up helping is playing around with the zooming in and out buttons as indicated by the red circle below:

![Capture](https://user-images.githubusercontent.com/24267968/72263741-c24b0480-3619-11ea-9b46-d7ee687a7223.JPG)

This seems to have an effect on the small "zoom in" window which allows to input data points more accurately...
