### ISSUE TITLE
Labelling individual series separately

### ISSUE THREAD

**Issue by aizenman** [ankitrohatgi/WebPlotDigitizer#19]
Hi There,

Once again, absolutely love the program.

One nifty feature that would be great to have would be the ability to label individual series separately.  That is, suppose I am trying to parse a graph like the one attached (not exactly the one attached, since that one has the numbers anyway, but it's useful for test purposes).  It would be nice to have a button that says, "first do series 1", do the blue bars, and then say, "now do series 2", and do the red bar.  

This is a less critical addition, since I can manually just do the blue bar, extract the data, then do the red bar, then extract the data... but would be nice!

/yga

![cd4](https://f.cloud.github.com/assets/6751894/2234811/ff72b9f6-9b3e-11e3-86e7-25524cb55924.PNG)

**Comment by ankitrohatgi** [comment]
I have added support for multiple datasets and bar charts over time. Both items need to be refined over time.

**Comment by aizenman** [comment]
Thanks so much!

By the way, I continue to love WPD - I think what you have done is such a
valuable service.
