### ISSUE TITLE
UI Request: Show Datasets Nested within Axes

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#191]
Currently, the UI for selecting axes and datasets does not show which datasets are associated with which axes.  The left box looks like this with a current file that I'm working with:

* Image
* Axes
   * Axis name 1
   * Axis name 2
* Dataset
    * Dataset name 1
    * Dataset name 2
    * Dataset name 3
    * Dataset name 4
* Measurements

I have to go to the dataset to confirm that it is within the axis that I mean for it to be within.

Would it be reasonable to show the datasets within the axis like:

* Image
* Axes
    * Axis name 1
        * Dataset name 1
        * Dataset name 2
    * Axis name 2
        * Dataset name 3
        * Dataset name 4
* Measurements

As a second request here:  It would also help if axes with no datasets and datasets with no data were shown differently (perhaps the name is colored red).  That would help give a to-do list for me to fill.

**Comment by ankitrohatgi** [comment]
The axes and dataset are separated to make it easy to switch axes on a dataset when needed. If I change the tree structure then have to also add option to move datasets between these and that's a lot more complicated thing to do in code.
