### ISSUE TITLE
Feature Request: Support Varying Ranges with Ternary Diagrams

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#193]
Ternary diagrams currently only support ranges of values that are either 0 to 1 or 0 to 100.  It would be a useful generalization to allow user input of the ranges of variables for each scale.

**Comment by billdenney** [comment]
I think that this could fit in the current file format by using the "dx" and "dy" values for the points (https://github.com/ankitrohatgi/WebPlotDigitizer/pull/198/commits/de18400fac959753258c859793e05e2ce4f1a518#diff-d986e178689b38e49c66064448d8f4a3R64) then just scaling values from those values.

That said, as I'm thinking about this request more, I don't think I've ever seen a ternary diagram that wasn't measuring a fraction (0 to 1) or percent (0 to 100) of three things mixed together, so the request is probably less important overall.

**Comment by ankitrohatgi** [comment]
Yes, I have not seen any ternary diagram that isn't `0-1` or `0-100` range. If you see one, then feel free to reopen this issue.

**Comment by qwertz1988** [comment]
Hey, 

just found this feature request. 

I'm facing now this exact problem. I have liquidus projections for metal alloys (melting temperature vs. different metal composition). Actually most of them do not show the full 0 to 100 range. Most of them only show a minor range for one, two or three components.

Would it be possible to enter a custom range for all components, so I do not have to program it on my own?

Best and thanks so far
