### ISSUE TITLE
Have a separate graph type - bar graphs

### ISSUE THREAD

**Issue by aizenman** [ankitrohatgi/WebPlotDigitizer#20]
Hi there,

Bar graphs can be handled/hacked by X-Y charts in manual mode already, but I wonder if it might be useful to add them as a separate graph type.  

There are two major differences between bar charts and others:
  * X values tend to be discrete - if they are in fact numbers (as opposed to pure labels)
  * Automatic mode would require very different programming

I think this is a nice-to-have, since the current system works fine - but perhaps a good way to get more nontechnical users using your software!

Once again, thanks so much for your work.
/YGA

**Comment by ankitrohatgi** [comment]
Recently added support for this: http://arohatgi.info/WebPlotDigitizer/blog/posts/bars.html

This will be refined over time. If you have further suggestions for this, then feel free to open another issue.

Thanks!
