### ISSUE TITLE
wine Error when Installing Dev Version

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#209]
When I was working on #208, I found an issue with wine.  In that case, I didn't need wine, so I removed it, but we may want to change `wine` to either `wine-stable` or `wine-development`:

```
$ sudo apt install wine
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package wine is a virtual package provided by:
  wine-stable 3.0-1ubuntu1
  wine-development 3.6-1
You should explicitly select one to install.

E: Package 'wine' has no installation candidate
```

**Comment by ankitrohatgi** [comment]
Thanks for catching that, it should be `wine-stable`.

It's only needed when generating Windows Electron app for distribution from Linux (I don't own a Windows machine, so I just generate Windows version from Linux).
