### ISSUE TITLE
Image / Data mismatch

### ISSUE THREAD

**Issue by Nouk67** [ankitrohatgi/WebPlotDigitizer#215]
Hi 
your work is great and maybe I'm too dumb to understand how it's working.
In automatic extract the "dots" are Ok on the image, but when I look at the data the value are not coherent with the image (I'm 100 % sure that the calibration is Ok). 
images 1 and 2 you can verify it's not starting at - 9.8 and ending at 9.8
![image1](https://user-images.githubusercontent.com/66633051/84049415-b6872280-a9ac-11ea-8782-af6cc1541f5e.png)
![image2](https://user-images.githubusercontent.com/66633051/84049423-b9821300-a9ac-11ea-92e1-823f91e64004.png)
 the uploaded image is :
![REC_color](https://user-images.githubusercontent.com/66633051/84049711-0cf46100-a9ad-11ea-9882-070d5be17b87.png)

I guess it's problem related the moving average, the results are better with histogram
=> Am I doing something wrong ?

cheer Nouk

**Comment by ankitrohatgi** [comment]
If the values are not correct, then you should check the axes calibration. The easiest way to check is to make sure as you hover over the data, the number under the zoomed-in view on the right look correct.

It's hard to debug your issue just from this image btw - if you can share the project `.tar` then I can help better.

**Comment by ankitrohatgi** [comment]
Closing for now due to lack of information. Please reopen when you have further comments to add.
