### ISSUE TITLE
Need Calibration For Image Which Don't Have Axis & Data Correction of Same Sheet

### ISSUE THREAD

**Issue by HiddenJokar** [ankitrohatgi/WebPlotDigitizer#216]
**Hi Dear Sir Big Fan Of You and Your Work.**
I Have Multiple Issue To Report Here
**1-** How to Add Axis if i have image / graph which dont have calibrated axis lik e this image
![Test](https://user-images.githubusercontent.com/24751324/85220463-08747300-b3c5-11ea-83d7-b69f9cdda020.jpg)
**2 -** If i have a graph which has three lines to trace but on the same axis why dont we have same data graph when ploted. only graph fits wel for one curve if we add data of second curve it gets distorted. Is there any way we have one graph multiple lines and have calibrated data points so that if we draw on one sheet it does not get distorted?
regards

**Comment by nbehrnd** [comment]
To reply to your first question:

I would suggest you look for an image editor which is capable to read .jpg and may display for both horizontal and vertical direction a scale.  In the example below, I used [inkscape](https://inkscape.org/) with the default dimension of pixels (px).  As you equally see, _inkscape_'s reference point for (_x_ = 0, _y_ = 0) is in the top-left corner.

![at_origin](https://user-images.githubusercontent.com/19709084/85221291-34cac800-b3a2-11ea-9178-6a6bae41bdee.png)

Now, inkscape has this pointer-button (left column).  If activated, it allows you to determine (_x_,_y_) _in inkscape's coordinate system_ of the image currently loaded.  These values are reported in the bottom line.  You have to note this tuple for the origin (picture above, here about (37, 432)).  Then you do so for a reference point in the horizontal direction

![x_axis](https://user-images.githubusercontent.com/19709084/85221356-c89c9400-b3a2-11ea-872a-bc7a7872e2c7.png)

-- about (551, 433) --- and for one in the vertical dimension, too:

![y_axis](https://user-images.githubusercontent.com/19709084/85221363-deaa5480-b3a2-11ea-8be4-712de02ada15.png)

-- about (36, 263).

Allowing integer numbers only, and converting it to the coordinate system used in your image, this is like an origin at (0,0), the reference for _x_ at (515,0), and the reference for _y_ at (0,170).

Feed these data to the digitizer when asked to calibrate _x_<sub>1</sub>, _x_<sub>2</sub>, _y_<sub>1</sub>, _y_<sub>2</sub>.  Don't worry about stacking _x_<sub>1</sub> on top of _y_<sub>1</sub> -- the program is robust enough to remember them as two points which just happen to share the location of (0,0).  Proceed as usual; select the colour of interest, pick a suitable pen width, and mark the trace which eventually will identify the curve:

![extraction](https://user-images.githubusercontent.com/19709084/85221544-f9c99400-b3a3-11ea-9a4f-40df59eba71e.png)

The `.zip` below contains both the `.cvs` of one extracted curve,  as well the project `.tar` to continue working on this.
[results.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/4809254/results.zip)

I don't understand your second question well enough to equally answer this one.  If you don't mind, please add an illustration.

**Comment by HiddenJokar** [comment]
Thank You So Much Sir @nbehrnd For Brilliant Explanation on fixing & calibration of Graph  Axis.
Sir i want to know as you trace curve 1, Trace second curve Too then draw these two curves on the same axis. one curve is drawn exactly as is graph but second curve is not same as in original figure. SO question is how can i draw these two above curves on the same axis by same calibration. because the x values of both curves are different. may be i'm unable to explain but i want these two exact curves on the same axis in Excel or some other graph plotting software.    Here is the trace of both curves 
[Default Dataset.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/4844289/Default.Dataset.zip)

**Comment by nbehrnd** [comment]
As you mention a spreadsheet program as tool, and the two _qualitative_ curves plot are described as proportional to a value derived from _N_, you may just create a table with four columns.  Namely
- one about  _N_ with real numbers greater than zero
- one computing the inverse number of the square root of N.  In [gnumeric](www.gnumeric.org) like `=1/sqrt(A3)` for a cell in the third row, assuming _N_ were deposit in column A.
- one computing the inverse of _N_<sup>3/4</sup>, in gnumeric's syntax equivalent to  `=1/(A3^(3/4))`

At this point, plotting the two, you will recognize a need to move one of the two curves in vertical direction.  Thus, 
- create a fourth column to perform a constant subtraction, e.g., by 20, of the values just computed.
Then just plot the curves with the plotter of your choice, and export them in a diagram in common

  ![test_plot](https://user-images.githubusercontent.com/19709084/86350654-8d2b8080-bc52-11ea-8406-ff5ba053261e.png)

Or, exporting the spreadsheet as a `.csv` file, as in the documents attached below in the archive, you may reach out for a more programmatic approach like [gnuplot](http://gnuplot.info/), starting with set of instructions like below

    set terminal svg`
    set output 'testplot.svg'
    set title 'testplot'
    set xlabel 'N'
    set ylabel '{\symbol F}'
    set xrange [0:0.02]
    set grid

    plot 'test.csv' using 1:2 title 'curve A' with line, 'test.csv' using 1:4 title 'curve B' with line
    exit

 to yield a `.svg` you may process further e.g., in `inkscape`.  This may be more portable than getting started in libraries like [matplotlib](https://matplotlib.org/).

[test_set.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/4864206/test_set.zip)

**Comment by nbehrnd** [comment]
Suggest @ankitrohatgi : Possibly the issue is resolved and this thread may be closed.
