### ISSUE TITLE
trouble to record distances on text window

### ISSUE THREAD

**Issue by Luxy-shi** [ankitrohatgi/WebPlotDigitizer#217]
When calibrating axis (map) the first time on a picture, everything is ok, but when I tweak the calibration and take the distance measurements, they are shown on the picture but not in the text/csv window. Can you help me?
Thanks

**Comment by nbehrnd** [comment]
Dear Luxy-shi,

I'm not sure if I understood you correctly and thus were able to help you.
However, save your project (File -> Save Project) as a .tar archive which
then contains both the raw data (the image) and the extracted data (as
far as already processed by the digitizer) for a deposit here as a minimal
work example.

The .tar format might not among the file formats your operating system is
capable to trade with, or / and GitHub accepts when filing an issue.  Yet,
a work-around to share these data here could be to «compress» this archive
as a .zip archive as an outer shell.  In other words, if your project
initially was exported as «test.tar», you could drop «test.tar.zip» here.

This may help others to identify where help may be offered.

Norwid

**Comment by ankitrohatgi** [comment]
Hi Luxy-shi,

I wasn't able to reproduce the bug like you described (perhaps sharing the .tar like @nbehrnd suggested would help).

However, when trying a few things, I did hit a possibly related minor bug. I have pushed a fix for this just now and updated the online version. Lmk if that works. If not, then please reopen this issue.

Cheers,
Ankit
