### ISSUE TITLE
troubles to record distance measurements -2

### ISSUE THREAD

**Issue by Luxy-shi** [ankitrohatgi/WebPlotDigitizer#218]
Hi, here again because the trouble still persists. I am attaching the .tar file zipped as you suggested in the previous request.
I try to explain it again. I load my picture containing multiple graphs, where I have to measure bar and error bar. For each graph, I have to tweak axis calibration both for bars and error bars (map distances). What I do is to clear all data before tweaking the axis on a second graph in the same picture (here no problem). The problem is when I take new distance data on the new calibration (on the new graph). Apparently the distances are recorded because they appear on the graph. Nevertheless, when I open the window to view the data, the window is empty, blank. The only solution is to reload the image and do again the calibrations.
[wpd_project.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/4901075/wpd_project.zip)

I hope you can help me. Thank you

**Comment by ankitrohatgi** [comment]
Ah, thanks for explaining it again. I am able to reproduce this issue now. I'll take a look.

**Comment by ankitrohatgi** [comment]
@ewchow / @billdenney  - appears the `Clear All` logic for measurements broke alongside the multipage code changes.

**Comment by ankitrohatgi** [comment]
@Luxy-shi , can you try the web version again and see if the bug persists? Thanks!
