### ISSUE TITLE
Recommendation: Add snipping tool so we can snip image right from paper or website

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [ankitrohatgi/WebPlotDigitizer#221]
Thanks for the useful tool! I would recommend adding an image snipping tool to the software so the user can take snapshots of figures/graphs directly from papers and websites.
Best,
Daniel

**Comment by eceforge** [comment]
I think a good alternative to this (that would likely require less work) would be to just allow pasting in an image from the clipboard. I know firefox already has a image snipping tool built into it, no need to recreate work. 

Also this tool in general is absolutely fantastic!

**Comment by ankitrohatgi** [comment]
Hi, pasting from clipboard is already supported. Just give it a try :)

As for snipping tool - the HTML5 API makes it hard to implement this unfortunately :( A true native application would be able to do this easily.
