### ISSUE TITLE
Database Duplicating itself

### ISSUE THREAD

**Issue by jpv190** [ankitrohatgi/WebPlotDigitizer#224]
Databases are duplicating themselves and coming back even you delete them. If you try to delete one, it actually delete both. Both have the same data.

![WebDigitizer Bug](https://user-images.githubusercontent.com/14959111/90677366-4a862d80-e22b-11ea-924c-15b68415b9be.PNG)

**Comment by ankitrohatgi** [comment]
I was able to reproduce this bug today. I will take a look, thanks for reporting!

**Comment by ankitrohatgi** [comment]
My steps to reproduce this issue:
- Load WPD
- Load JSON project from somewhere
- Add a new axes, it will duplicate and subsequent new datasets will duplicate

**Comment by ankitrohatgi** [comment]
Hi, I updated the web version with the fix. Please reopen this issue if you see something like this again.

I will update the desktop versions sometime soon.
