### ISSUE TITLE
Incorrect Data Export from Long Plot

### ISSUE THREAD

**Issue by rsh52** [ankitrohatgi/WebPlotDigitizer#225]
Hello,

I am extremely impressed with the automatic data point matching of this software and think it will be very useful for a project I have. The project involves digitizing EKG rhythm waveforms and so the "plot" itself is very long horizontally (example snippet below):

![image](https://user-images.githubusercontent.com/38384694/91311470-21145700-e781-11ea-85b4-f3e15f3839d6.png)

Unfortunately whenever I view the data it seems to constantly increase beyond the axis limits I've specified (in this case a block of data in the strip is 0.2s horiztonal, and the 0/30/60 bar shows the scale vertically). When plotting the data I get this:

![image](https://user-images.githubusercontent.com/38384694/91311651-528d2280-e781-11ea-9357-64f5f214281a.png)

I have tried this on numerous images we have and attempted using the transformation equations to convert the data but with the same overall result. I have also tried increasing the X-axis scale to the end of the full image. Are the axes supposed to be defined for the entire viewing area or can a simple scale be supplied?

Thank you,
--Rich

**Comment by ankitrohatgi** [comment]
Hi, would it be possible for you to share the project (.tar) file? I suspect something's off in the axes calibration, but I can't pin point the issue.

**Comment by rsh52** [comment]
Sure sending now with same subject line as as issue title. Thank you for checking!

**Comment by ankitrohatgi** [comment]
I replied in more detail over email.

Here's the summary:
- For now, please try calibrating with x and y points for calibration being as far apart from each other as possible.
- I can look into adding an option to turn off rotation correction of plots. Looks like in such low resolution (at least in one direction) images, it's better to assume x and y axis are aligned to horizontal and vertical directions

**Comment by rsh52** [comment]
Reflecting our email exchange:

It would be very helpful to turn off any "auto-rotation" feature if I can assume/guarantee that no rotation is needed. I will also try and expand the axis scale definitions where possible due to the low resolution.

**Comment by ankitrohatgi** [comment]
Hi,

I have added an option for turning off automatic rotation correction - I was able to confirm that this fixes your issue. This is not in the released version yet, but I can push it in a couple of days for you to try.

![image](https://user-images.githubusercontent.com/415640/92707918-8da75e00-f30a-11ea-8b8e-808fa069ab39.png)

Regards,
Ankit

**Comment by rsh52** [comment]
Fantastic! Will look forward to testing this out next week, it will be immensely helpful. Appreciate the speedy turnaround

**Comment by ankitrohatgi** [comment]
Hi, you can give the latest code a try here: https://apps.automeris.io/wpd_latest/

**Comment by rsh52** [comment]
Been messing around with it for the last couple of hours and it looks great, exactly what I expect. If I notice anything off with it I'll let you know but otherwise thank you SO SO much for working on implementing this feature. Any chance it will be incorporated in the downloadable version?

**Comment by ankitrohatgi** [comment]
Hi, sorry about the delay on this. I hope to release the desktop versions soon. If you need a copy sooner, then I can provide a one-off build in the mean time.

**Comment by rsh52** [comment]
Not a problem, I have the new link saved and will just be on the lookout for when the new version release is available. Thank you!
