### ISSUE TITLE
Exported data is empty and format function does not work 

### ISSUE THREAD

**Issue by HenryPrzygocki** [ankitrohatgi/WebPlotDigitizer#228]
After the latest update **I'm unable to format data**, which in my case is a single space for data separation and 3 fixed decimal points. 
Also **the "format" button became non responsive**. 
My procedure after calibrating axes was to go in "View Data", format it as described above and download data. The .csv file now comes empty or with the wrong data format. I've tried downloading the Linux version and the issue is also there. 
Just to reinforce, the problem is both on the desktop application **AND** in the online version, therefore I ruled off my computer as the source of the problem. Furthermore, **I've been doing the same thing I did before the update**, so It's not an issue of not knowing how to use it.
I really need this tool for my master's dissertation! Every help is appreciated!

**Comment by ankitrohatgi** [comment]
@HenryPrzygocki - I am not able to reproduce the issue with your description. Can you share the project file where this can be reproduced or provide more info e.g. axes type, number of datasets etc.?
