### ISSUE TITLE
NaN for y-axis 

### ISSUE THREAD

**Issue by merf3** [ankitrohatgi/WebPlotDigitizer#229]
After calibrating the first graph,

![image](https://user-images.githubusercontent.com/71489562/93571810-41f15600-f995-11ea-9493-cfb7b1c80f46.png)

I get NaN for the y axis.
Calibrating 500 to 3500 for x and 0 to 0,7 for y.

Am I missing something?

**Comment by merf3** [comment]
It works with the second graph, so I am guessing, I cant go for 0 to 0,7 and need other dimensions?

**Comment by merf3** [comment]
Found a solution by just writing 0 to 7. Can just divide later! So you can close this and thanks anyway <3 !

**Comment by ankitrohatgi** [comment]
Glad you figured it out. In future, please share the project `.tar` file otherwise it's impossible to reproduce the issue.
