### ISSUE TITLE
Auto extract not working

### ISSUE THREAD

**Issue by Phyks** [ankitrohatgi/WebPlotDigitizer#23]
Hi,

On the demo website, the auto extract feature is not working for me. I have some "l.binaryData and b.binaryData which does not exist" errors in the javascript console.

Maybe I missed something… I tried with both Firefox and chromium, up to date.

I attach the graph I tried it on :
![ibg_below](https://cloud.githubusercontent.com/assets/3856586/3094058/53283486-e5b8-11e3-989d-25ac2d9caaba.png)

Thanks

**Comment by hyderfathima** [comment]
Auto Extraction is not working in google chrome. 
This link is not also working.  (http://arohatgi.info/WebPlotDigitizer/beta/)

**Comment by ankitrohatgi** [comment]
@hyderfathima - this thread is 6+ years old. The links here are obsolete. Please check the links you are using.
