### ISSUE TITLE
Save axis and Algorithm parameters

### ISSUE THREAD

**Issue by Fatdz** [ankitrohatgi/WebPlotDigitizer#236]
Hello,

I have multiple jpeg files which I want to digitize.
I want to use same digitizing parameters such as Align X-Y Axes (X1X2,Y1,Y2) , Algorithm (X_min, deltax Step,...) for all files.
When I loaded new file, the parameters set for a  previous file disappear. So,  I have to repeat the setting of these parameters for each loaded file. Please,  how can I  keep these parameters for all files, in order to avoid repetition of setting which is time consuming.

Cheers

**Comment by ankitrohatgi** [comment]
Hi - one way to do this is to save your work as JSON, load the next image and then import the JSON project. This should not clear the new image.
