### ISSUE TITLE
Negative values on X axis give an NaN error

### ISSUE THREAD

**Issue by silviulaurentiu** [ankitrohatgi/WebPlotDigitizer#240]
When negative numbers are used on X axis and logarithmic scale, the x axis values are displayed as NaN

![5tjb3LDFuO](https://user-images.githubusercontent.com/14875058/104340688-a1a1dd00-5501-11eb-95c3-b8c9fb0f2fca.gif)

**Comment by ankitrohatgi** [comment]
Closing this since this is a duplicate of #240
