### ISSUE TITLE
Negative values on X axis are displayed as NaN

### ISSUE THREAD

**Issue by silviulaurentiu** [ankitrohatgi/WebPlotDigitizer#241]
When negative numbers are used on X axis and logarithmic scale, the x axis values are displayed as NaN

![5tjb3LDFuO](https://user-images.githubusercontent.com/14875058/104340688-a1a1dd00-5501-11eb-95c3-b8c9fb0f2fca.gif)

**Comment by ankitrohatgi** [comment]
Hmm, yeah, this is a bug.

For the time being, you can probably skip the negative sign during data extraction.

**Comment by ankitrohatgi** [comment]
Hi, I merged a fix that you can try here: https://apps.automeris.io/wpd_latest/
