### ISSUE TITLE
Image not exported in .tar package when imported as copy-past (CTRL+V)

### ISSUE THREAD

**Issue by c-buzz** [ankitrohatgi/WebPlotDigitizer#243]
The problem described into the title arises when exporting a project (File/Save Project) based upon an image that has been loaded through a CTRL+V input. In this case, the generated .tar contains only the start.png image.
If the project is loaded again through the .tar package in a second moment, the axis as well as the datased will be maintained but referred to the default start image.

The software works fine if the image was loaded through the menu entry point: in this case the image is correctly saved into the exported package

**Comment by ankitrohatgi** [comment]
Thanks for reporting this, will look into it soon!
