### ISSUE TITLE
Blob detector malfunction

### ISSUE THREAD

**Issue by helena3110** [ankitrohatgi/WebPlotDigitizer#247]
Whenever I use the blob detector algorithm, although I can see the points selected in the image, I can't view or download the data. With every other algorithm it works fine. Any ideas?

**Comment by nbehrnd** [comment]
Suggestion:  To illustrate and document your current problem with the
digitizer, identify an image which may be shared here and where you
experience this particular problem.

For convenience, I suggest you wrap it into a .zip archive -- which
is a format supported by GitHub's issue reporter.  In this case --
submitting a .png -- it is not (so much) about .zip as a file
compressor.  Note, if you chose to do so, this very file can't be an
attachment of an e-mail, you have to add it running a GitHub session.

**Comment by lenaro12** [comment]
![Error_blobdetector](https://user-images.githubusercontent.com/81262239/112296479-b8884c80-8c73-11eb-9fa9-c6af03f92c5d.PNG)

**Comment by nbehrnd** [comment]
Your understanding of the purpose of the blob detector differs from the one by the author
of the program.  Hence the digitizer does not work in the fashion you expected.

You are better off starting the digitizer, reading the image file again.  In the next menu,
choose instead the very first entry «2D (X-Y) Plot» which allows you to digitize _a curve_.
It is irrelevant for the digitizer if these curves possess markers as dots, or triangles like
in your case, or none at all. Depending on the increments for abscissa and ordinate you
choose and the input image, the digitizer then may identify points on your trace much
closer to each other / much wider apart from each other than the dots and triangles of
the original illustration. The resolution of the screen photo shared by you however is too
low to run the digitizer reasonably well, but the [tutorials](https://automeris.io/WebPlotDigitizer/tutorial.html) may guide you. 

The blob detector however is handy if you are interested e.g., in the position of dots
and blobs not related to a function / recording in an image, and eventually to count
their number.  See equally section 5.3.5 of the [manual](https://github.com/ankitrohatgi/WebPlotDigitizer/blob/master/docs/latex/userManual.pdf) and an [earlier blog post](https://automeris.io/WebPlotDigitizer/blog/posts/blob_detection.html) by the
author. The application on a simple image is shown in the .zip attached below, too.

[test_set.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6197266/test_set.zip)

**Comment by ankitrohatgi** [comment]
@helena3110 - I made some fixes to blob detector algorithm in the most recent release. Please re-open this if you are still seeing issues.
