### ISSUE TITLE
Feature Request: Extract range of error bars

### ISSUE THREAD

**Issue by ttkummer** [ankitrohatgi/WebPlotDigitizer#248]
In my line of work error bars are generally included in scatter (X,Y) and bar graphs. These usually represent standard error of the mean, or standard deviation, but sometime something else or even just range. It would be super helpful, in terms of understanding the underlying data, to be able to extract the ends of these error bars. Unfortunately these error bars can take several forms, extending above, or below the data, or both, and may be simply a line, or a line ended with a small cross bar. It may be helpful to give the user a way of selecting the direction (up, down, both) of the error bar and the shape (line, line with cross-bar) to help with data extraction.

**Comment by billdenney** [comment]
Is this the same as #51 ?

**Comment by ttkummer** [comment]
It seems yes, my request is essentially a part of #51. Add capacity to identify tops and bottoms of error bars (or just too or bottom, as they’re symmetric the other could be determined with a simple calculation vs the mean)



Terry

Sent from iPhone. Please excuse type-o’s
________________________________

**Comment by nbehrnd** [comment]
While vertical error bars seem to be the more frequent ones (e.g., box whisker plots)
it were desirable if the implementation would retain the opportunity to extend this type
of processing for error bars along the abscissa, too:

![errorbars 1](https://user-images.githubusercontent.com/19709084/112730528-f6ae9600-8f29-11eb-8910-04d2b8985475.png)

([credit](http://gnuplot.sourceforge.net/demo_5.4/errorbars.html)

**Comment by billdenney** [comment]
@nbehrnd , The general idea of data points that are grouped together is part of the intent of #51.  Relevant to @ttkummer 's comment above, I share the goal though since error bars are not always symmetric (e.g. interquartile ranges), I prefer the general solution of collecting multiple points up, down, left, right, or wherever they are relative to each other.

**Comment by nbehrnd** [comment]
I see, like in the plot below:

![box](https://user-images.githubusercontent.com/19709084/112731521-a3d7dd00-8f2f-11eb-997c-c11fedaac6ea.png)

by Ferreira _et al._ in Educación Química (2016) **27**, 209--216, [doi 10.1016/j.eq.2016.04.007](http://dx.doi.org/10.1016/j.eq.2016.04.007) (open access).

**Comment by ttkummer** [comment]
Yes, I'd forgotten that there are examples of non-symmetric error bars.
Being able to find values for the ends of all these
error/interquartile/other indicator lines would be extremely helpful.
For example, in my field again, error bars mostly represent standard error
of the mean. If one also knows the sample size (generally reported), and
the mean (which weboplotdigitizer already extracts), then one can calculate
the standard deviation easily.

**Comment by billdenney** [comment]
This has been implemented as part of the new point group feature.

**Comment by ankitrohatgi** [comment]
hi @ttkummer - lmk if Eric's recent contribution about Point groups works for you for now: see https://github.com/ankitrohatgi/WebPlotDigitizer/pull/254 for details.
