### ISSUE TITLE
blob detection looks like incomplete

### ISSUE THREAD

**Issue by nbehrnd** [ankitrohatgi/WebPlotDigitizer#260]
Curious about the feature about «blob detection» mentioned [here](https://automeris.io/WebPlotDigitizer/blog/posts/blob_detection.html) (loading an image -> plot type «image» -> algorithm «blob detector» both the reference image (circles, stars, characters) of your post as well one consisting of polka dots only were submitted to the online version of the digitizer.  At present, only the (x,y) coordinates of the centre of these blobs are identified.  The, e.g., report of integrated area of these individual blobs *looks like* defunct:

![polka_dot_use_small](https://user-images.githubusercontent.com/19709084/120026628-deb6c980-bfe1-11eb-984f-6d4281bdffcc.png)

Are these two illustrations what the blog post considers as «too noisy»?  Was the blob detection an experimental feature, a test case only eventually dropped in favour of other functionality of the program?

[reference_image.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6562772/reference_image.zip)
[polka_dots.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6562774/polka_dots.zip)

**Comment by ankitrohatgi** [comment]
Hi, this looks like a bug. I didn't have a specific use case for blob detection when I added it, but figured it would be useful in some situations. I didn't develop on it beyond the first implementation - which seems to be kind of broken right now :/
