### ISSUE TITLE
Keyboard shortcuts not working when focus is lost

### ISSUE THREAD

**Issue by c-buzz** [ankitrohatgi/WebPlotDigitizer#262]
Not sure it's a real bug, but when the focus is not proper, the keyboard shortcuts do not work.

For reproducibility:

```
OS: Lubuntu 20.04
Mode: XY Graph
Shortcut tested: A, D, S for adding, adjusting and removing points.
```

If it was meant to be focus-dependant, it would be easier and more useful, in my opinion, to have shortcut available throughout the app.

**Comment by ankitrohatgi** [comment]
Hi, the keyboard shortcuts are focus dependent. It was made so to avoid accidental mode changes when interacting with other controls.
