### ISSUE TITLE
Logarithmic Scale not scaling appropriately

### ISSUE THREAD

**Issue by dev3011** [ankitrohatgi/WebPlotDigitizer#266]
Hey,
I'm using v4.4 on Windows.
I have a graph with one axis being logarithmic.
![graph](https://i.ibb.co/6J2bMrh/graph.png)
I set the axes like this:
![axes](https://i.ibb.co/vm7Q8Wh/axes.png)

However, the resulting scale is different from the one in the graph. It starts with 1E-5 and ends with 0.99 correctly but the resulting scale is not logarithmic. I think the resulting scale is just linear.

This is the image and project file:
[image](https://www.file-upload.net/download-14636674/graph.png.html)
[project_file](https://www.file-upload.net/download-14636675/graph_gh.tar.html)

**Comment by nbehrnd** [comment]
The plot is Cartesian, the scaling of the abscissa is linear; but the scaling of the ordinate does not looks logarithmic (nor linear).  Say one would constrain the representation of the data to the decade of 0(0.1)1.0 along the ordinate. Then, the distance about first increment of 0.1 between 0.0 and 0.1 should be *much* larger (when counting in pixels) then the distance (in pixels) about last increment of 0.1 between 0.9 and 1.0.  Here, however, the distance (counting in pixels) between 0.9 and 1.0 is considerably larger than e.g., between 0.8 and 0.9.

See, for example, about the two decades 0 to 0.1 to 1 as *if* the original plot were correct:

![Default_Dataset](https://user-images.githubusercontent.com/19709084/126077906-104ce898-3a5e-4768-8269-1a633d1e2fcf.png)

Thus, check if you may obtain the data from a different plot.

[test_run.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6836744/test_run.zip)

**Comment by ankitrohatgi** [comment]
Hi, to add to @nbehrnd's answer - I see that the y-axis labels have some hyperbolic relationship to the image pixels and not logarithmic:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/415640/126108661-d213a9dd-0261-4662-b2b3-8f1be70d0ef4.png">

so it's not a surprise that the logarithmic scaling option does not give the correct results.
