### ISSUE TITLE
Only FILES and HELP menu in web version

### ISSUE THREAD

**Issue by jumpjack** [ankitrohatgi/WebPlotDigitizer#273]
I can't see AXES and other menus in web version using Chrome.  How can I remove the background grid?
Same happens in Windows64 version.

**Comment by nbehrnd** [comment]
You may substantiate your observations by adding a screen photo, or
two.  If these don't fit into the issue reports /as such/, you may
stash them into a .zip archive, and submit this as an attachment to
your question (perhaps already including the troublesome illustration,
too).  Though I think basic tutorial video actually is a recording
using the chrome web browser.

Re the removal of a grid your to be digitized image contains:  Did
you read the manual (section 4, pages 13 and 14) about the topic?

**Comment by ankitrohatgi** [comment]
Hi, I think you might be comparing the YouTube video tutorial with the WebApp. The video tutorial was made quite a few years back when I had more menu items. The current version only has the two `File` and `Help` menus:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/415640/149742154-bb600bc8-e491-44d8-bc47-6aeaef3dee30.png">

**Comment by jumpjack** [comment]
Yes, now I see "remove grid" button under AXES section.
Do you think it is possible to remove this grid?

![immagine](https://user-images.githubusercontent.com/1620953/149809566-e8a3f80d-4ae7-4b39-9eaf-88606a6a24c2.png)
