### ISSUE TITLE
Windows 64 bit version just shows blank white screen

### ISSUE THREAD

**Issue by bellzw** [ankitrohatgi/WebPlotDigitizer#274]
After downloading and unpacking the zip file, clicking on the exe just results in a blank white screen.  The screen responds to the X control to close it.

Computer: Lenovo Yoga 14, 
OS: Windows 10 64-bit, Windows 10 Home edition, V. 21H2 build 19044.1466.

**Comment by ankitrohatgi** [comment]
Hi, I tested this on a Windows 10 Home Edition just now and it works fine for me. Perhaps there was some issue during download or zip file extraction etc.?
