### ISSUE TITLE
Grid Removal/Detection

### ISSUE THREAD

**Issue by ankitrohatgi** [ankitrohatgi/WebPlotDigitizer#28]
Detect grid lines and ignore interfering lines during automatic extraction.

**Comment by mhanders88** [comment]
The grid removal option would be a great option when implemented. Love the app! Keep up the good work!

**Comment by ankitrohatgi** [comment]
Thanks! I had started on the grid removal, but I didn't like my first attempt as I think it could be automated further. I'll take another shot at it soon.

**Comment by analyser-** [comment]
Yeah! I come here to ask the same. Actually, I've an image that has the grid with the same color of plot, so that's rather impossible to use the automatic data's point detection.

Very good app! Thanks!

**Comment by ankitrohatgi** [comment]
Thanks! I just need to find some time to devote to this and I should be able to get this to work in the app. I have experimented with a few strategies that will work.

**Comment by ankitrohatgi** [comment]
This has just been added to the code. This will be available in the next release (no ETA yet). The feature just needs some more testing etc.
