### ISSUE TITLE
x stpe

### ISSUE THREAD

**Issue by Babizinho** [ankitrohatgi/WebPlotDigitizer#284]
On my simple xy graph, "averaging window" works fine, but I need y readings for integer x values and "x step" doesn't work. When I click "Run", nothing happens. I have tried changing x step value and other changes, to no avail. How do I get "x step" to actually run?

**Comment by nbehrnd** [comment]
May you illustrate the issue by submission of an additional .png with about the diagram in question?

**Comment by Babizinho** [comment]
Thanks for prompt response. Here's the graph image... 
![AGe of onset CENTRE](https://user-images.githubusercontent.com/104843889/166575793-a9dda142-1f07-4280-b95f-4d603d593324.png)

**Comment by nbehrnd** [comment]
Contrasting to the abscissa (the horizontal axis), the ordinate (vertical dimension) lacks tics, the little lines of graduation.  Given the style of the font on the axes which are lining (contrasting to old style figures like the year on a penny with different base and vertical dimension ([Wikipedia](https://en.wikipedia.org/wiki/Text_figures))) my assumption these (missing) tics were approx. at the level where where the downward stroke of the «5» and the arc meet.  (Perhaps screen photo 02 (zip archive below) illustrates this better.)  _Because this is an approximation, my recommendation is: if you happen to have access to the original plot with tics on both axes, repeat the digitization._

The default averaging digitization works, as described by you.  For the one with x = 0, 1, 2, 3, ... you are going to need to adjust the levels of y_min and y_max to extend _beyond_ the interval [0...1].  Once set, the digitizer works just as well as one is used to.

[dataset.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/8616847/dataset.zip)

**Comment by nbehrnd** [comment]
Note: For some reason, you already closed _this_ thread some hours ago, yet later added the plot in question. On the other hand [this issue](https://github.com/ankitrohatgi/WebPlotDigitizer/issues/285), likely equally aiming to resolve the same question.  Consider to close the other one.
