### ISSUE TITLE
Browser Error on Application Load

### ISSUE THREAD

**Issue by ukendiran** [ankitrohatgi/WebPlotDigitizer#287]
Loading application, please wait...

Problems loading? Make sure you have a recent version of Google Chrome, Firefox, Safari or Microsoft Edge installed.

Please find the above error occure.

**Comment by ankitrohatgi** [comment]
Hi @ukendiran - can you provide any more info on this? What browser/OS are you using? Or was this on the desktop version?

**Comment by ankitrohatgi** [comment]
Closing this for now. If you have more info on this then you can reopen this issue.
