### ISSUE TITLE
MapAxesCalibrator set origin (0,0) at bottom left of image

### ISSUE THREAD

**Issue by citpeks** [ankitrohatgi/WebPlotDigitizer#290]
Currently a **map with a scale bar** has the origin (0,0) at the _top left_ of the image.  Images plotted from the selected points are upside-down (vertical reflection).  This could be fixed by setting the origin of a **map with a scale bar** to the _bottom left_ of the image. The following image illustrates the problem.  The plotted image is upside-down.  The change would only involve about five lines of code in axesCalibration.js to set the origin in wpd.MapAxesCalibrator. 
![lake-in-india01](https://user-images.githubusercontent.com/110055510/181077649-558a7ffe-d503-483d-87b0-6909d6a94f87.jpg)

**Comment by ankitrohatgi** [comment]
Hi, this makes sense. I could add an option to change the origin for those who want the origin to be at the bottom left.

**Comment by ankitrohatgi** [comment]
Added an option to switch the origin:
![image](https://user-images.githubusercontent.com/415640/181177359-6f79aa12-c860-406b-8c32-969e3146845c.png)

This will be available in the next release version of WPD.

**Comment by citpeks** [comment]
Thank you very much. After I emailed you, I opened a Github case.  I am
glad that you expedited this.  I am in the process of doing a YouTube
review of some plot digitizers for mapping lake areas. WebPlotDigitizer is
the best and the easiest to use.  This change will make my project much
easier.

I am using digitization as a tool for the study of the Carolina Bays by
applying least squares fitting of ellipses, as described in this video:
https://youtu.be/A1gLaIIACnI

I really appreciate your help.

Regards,
Antonio Zamora

**Comment by citpeks** [comment]
Hello Ankit,

This video discusses WebPlotDigitizer for use on the Carolina Bays. I
mention the quick response that you gave to my Github request. I am looking
forward to the new version with the option for the origin at the bottom
left of the image.
https://youtu.be/ENyvwbZoSik

I am also a chemist.  Here is my CV:
https://www.scientificpsychic.com/az.html

Thank you,
Antonio Zamora

**Comment by ankitrohatgi** [comment]
Hi, I might take some time to test and distribute the next version officially. In the meantime, you can try the unreleased version here: https://apps.automeris.io/wpd_latest/

**Comment by ankitrohatgi** [comment]
Btw, thanks a lot for sharing your video! It's great to see how this software is being used!

**Comment by nbehrnd** [comment]
@citpeks @scipython En route for some different topic (related to Python) I became aware of Christian Hill's [blog post](https://scipython.com/blog/direct-linear-least-squares-fitting-of-an-ellipse/) about fitting (partially tracked) ellipses.  It could be of interest for both of you, hence a tentative inclusion of him in cc (his [GitHub landing page](https://github.com/scipython)).
