### ISSUE TITLE
WebPlotDigitizer crashing due to electron

### ISSUE THREAD

**Issue by sambo57u** [ankitrohatgi/WebPlotDigitizer#292]
When one starts WebPlotDigitizer on machines with Nvidia GPU it crashes:
FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

This is a known error that was fixed in electron updates. It effects other apps like zoom, atom editor. zoom has fixed the problem.
This is on Fedora 36 Linux.

Using the option --disable-gpu-sandbox solves the problem but without the use of sandbox. Thanks!

**Comment by ankitrohatgi** [comment]
👀  Thanks for raising this!

**Comment by sambo57u** [comment]
I see that electron is updated. Could we get a new version for desktop linux use please....Thanks!

**Comment by ankitrohatgi** [comment]
I made that change for the version in development which I plan on releasing soon as soon as I get some time to test some other changes that went in recently. 

In the meantime, I can try to release a patched version when I get a chance this weekend.

**Comment by ankitrohatgi** [comment]
Hi, I have a patched version, but not posted on the website yet. If possible, then can you give this a shot and see if this works? https://automeris.io/downloads/WebPlotDigitizer-4.5-linux-x64-electronfix.zip 

I was able to reproduce the problem on my Ubuntu desktop with the official version and this version worked fine so hoping this works for you.

**Comment by sambo57u** [comment]
Hi, I confirm that the fixed version is working fine on Fedora 36! Thank you. WIll there be a new release coming soon or should I just use this in the meantime?

**Comment by ankitrohatgi** [comment]
Please continue using this for now. The next version needs some more testing - I can't commit to a specific date right now unfortunately.
