### ISSUE TITLE
Desktop version for Apple Silicon is "damaged"

### ISSUE THREAD

**Issue by ankitrohatgi** [ankitrohatgi/WebPlotDigitizer#293]
Users may see the following when trying to run WebPlotDigizer on Apple Silicon:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/415640/190959810-cfc4cb97-03cb-4f3a-9123-91672a091588.png">

It appears MacOS requires applications to be signed and notarized by the developer otherwise downloaded applications are marked as "quarantined".

Temporary workaround:

In terminal, please type:

`xattr -cr /path/to/WebPlotDigitizer-4.6.app`

@ankitrohatgi will update Apple Silicon package with a signed and notarized version soon.

**Comment by ankitrohatgi** [comment]
New build has been posted on the website now: https://automeris.io/downloads/WebPlotDigitizer-4.6-darwin-arm64-signed.zip

**Comment by Sumidu** [comment]
New Version also has a problem on Apple Silicon. This time I get the following error:
"You cannot open "WebPlotDigitizer", as this program is not supported on this Mac."
