### ISSUE TITLE
Rahul Gole - Dev Help

### ISSUE THREAD

**Issue by rgoolio32** [ankitrohatgi/WebPlotDigitizer#294]
Ankit,
I am interested in working with you on a project based on your technology. I sent you an email from rgoolio32@gmail.com to your Hotmail account, but I was not sure if you checked it. I hope this is not too forward, but I would love to chat; let me know. @ankitrohatgi

**Comment by ankitrohatgi** [comment]
Hello Rahul, thanks for your email and apologies for not replying sooner. This project is a side project that I work on in my free time and unfortunately I do not have the bandwidth necessary to collaborate with anyone on this at the moment. If you have any specific questions then please email me and I will try to respond if possible.
