### ISSUE TITLE
Ability To Set Number Of Days For A Circular Chart.  

### ISSUE THREAD

**Issue by daveparks23** [ankitrohatgi/WebPlotDigitizer#297]
Currently it seems to default to 7 days for a circular chart.  Maybe I am missing something.  Thanks for any help.

**Comment by ankitrohatgi** [comment]
Hi! Yes, the current circular chart recorder is very preliminary and only supports 7 days, but it can be changed. I started with 7 days as it was something others had requested and I had not personally come across too many circular charts. If you have some examples of the charts you are working with and willing to share then it would help make the implementation more flexible.

Thanks!

**Comment by The-Enzo** [comment]
Hey ankitrohatgi, I am looking for this as well we process several different charts ranging 7 day, 8 day, 15 day, 16 day and 30 day. I would be happy to share a few charts with you. I will send a few to your email address listed on your GitHub for testing.

**Comment by ankitrohatgi** [comment]
Thanks! That email address works.

**Comment by ankitrohatgi** [comment]
Hi, I never received any charts from you so I took no action on this until recently. Another user mentioned wanting to support 1 day charts and so now I have added 1 day and 7 day as two options. If you are still interested in other ranges then let me know. I am closing this out for now.
