### ISSUE TITLE
Redisplay the auto extract choices after you save and the reimport the project?

### ISSUE THREAD

**Issue by pluggedin2** [ankitrohatgi/WebPlotDigitizer#300]
Can't find any documentation for do this.

**Comment by ankitrohatgi** [comment]
The Automatic Extraction section should reflect the choices that were made when the project was saved (e.g. color, algorithm and parameters etc.). Are you looking for something that lists out these choices?

**Comment by pluggedin2** [comment]
Ankit,
Thanks for the response.
Actually I am looking to not having to reenter all the various
parameters just to rerun the same image with just a tweek or two
Is this possible?
Ed
