### ISSUE TITLE
Rotate Image inverts axes labels and the auto extraction drawings tool incorrectly draw

### ISSUE THREAD

**Issue by SamuraiChimp** [ankitrohatgi/WebPlotDigitizer#303]
After rotating and image 180 my axes labels appeared upside down.
![image](https://user-images.githubusercontent.com/127883614/225089727-e009b87c-6be2-40a6-aca0-449fd02d72ee.png)

Trying to use the box or pen tool for auto extraction would highlight a different part of the image than selected. Appeared inverted.
![image](https://user-images.githubusercontent.com/127883614/225090374-355eacc2-9831-4427-8c5e-46bf2bedbce0.png)

After running it would select the data correctly.
![image](https://user-images.githubusercontent.com/127883614/225090522-e79b7006-f8bd-4f20-857d-3b1120bddde8.png)

Going back to the pen tools "corrects" the highlight.
![image](https://user-images.githubusercontent.com/127883614/225090697-2b125a84-418f-45dd-bd6f-12af77224a11.png)

However, trying to highlight again is still inverted until reran.

**Comment by ankitrohatgi** [comment]
Thanks for reporting this. This has been fixed in the online version. The downloadable offline version will get updated in the next release. 

btw, the labels will still be upside down etc. Just the bugs associated with making the mask and measurements are fixed.
