### ISSUE TITLE
XY calibration is not take into account in OSX M2

### ISSUE THREAD

**Issue by elcolie** [ankitrohatgi/WebPlotDigitizer#304]
Version 4.6.0 (4.6.0)
OSx: 13.2 (22D49)
M2
I have calibrated the graph.
![image](https://user-images.githubusercontent.com/18206728/228446558-719fa913-7b94-4fc8-a899-065d68868437.png)

The program does see the first datapoint as 700. Which is beyond the 1100 which is the lower bound of my plot.
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/18206728/228446335-733a16e8-3b74-4802-8ad9-7d32d6ca9ce2.png">

**Question:**
How do I get the correct value?

**Comment by elcolie** [comment]
Close because I am unable to reproduce this.

**Comment by nbehrnd** [comment]
*These* values are about the pixels of the illustration.  Don't worry, continue to the point you collect the digitized data.

With four reference points\*:

![reference_points](https://user-images.githubusercontent.com/19709084/228454672-670218fd-3f95-4ff5-bd27-c7daadd4430d.png)

you get to something similar to

![digitized_data](https://user-images.githubusercontent.com/19709084/228454831-8e7e6958-fac1-4f6e-8313-6f44ff84fa0a.png)

\* My personal preference is to define reference points for abscissa and ordinate without an overlay (e.g., on the origin of the coordinate system), i.e. x1 and x2 *reasonably* accurate on the horizontal axis, but not necessarily *as much as equally well accurate* along the vertical one, for example.
