### ISSUE TITLE
Correct perspective distortions with script

### ISSUE THREAD

**Issue by phhoef** [ankitrohatgi/WebPlotDigitizer#306]
Hi,

I have several plots of a working area of a truck. These plots are photos taken with a camera of a mobile phone.
Obviously all images suffers from perspective distortion.

I was wondering if I can write a script that corrects the distortion based on the x,y axes calibration.
In that case I will always use the 2d xy plot method. When selecting two points on each axis, I think I could correct the distortion as I know, that both axes are right-angled.

Is that possible with a script? I do not see any API for manipulating the image, only on receiving datasets and stuff like that.

**Comment by nbehrnd** [comment]
@phhoef Do you know [hugin](https://hugin.sourceforge.io/), an example of a panorama stitcher?  The program allows you to tailor corrections e.g. for wide angle, or fisheye lenses and their distortions.  The individual profiles (which can be reused later) equally can be applied on single photos from non-DLSR cameras, too.  Including some test data to get familiar with the program and its workflows, I hence recommend the tutorials on [simple lens correction](https://hugin.sourceforge.io/tutorials/calibration/en.shtml) followed by [perspective correction](https://hugin.sourceforge.io/tutorials/perspective/en.shtml) as an entry.

Back in time of analogue-only large-format plane cameras (e.g. plates of 4x5", or 6x9"), a correction of the perspective like the example of the Egyptian wall too close to the lens often was addressed with [tilt-shift technique](https://en.wikipedia.org/wiki/Tilt%E2%80%93shift_photography) and [Scheimpflug rules](https://en.wikipedia.org/wiki/Scheimpflug_principle), especially in architectural photogrammetry.  Nice to see today we've two approaches partially complementary of each other.

**Comment by phhoef** [comment]
@nbehrnd thanks for your reply. I was not aware of hugin. The problem is, that I will get many photos from different cameras and I would have to create a profile for each. Though, it might be still an improvement, as I will get probably a few photos from the same camera..
I was hoping to solve it through WPD, as the 4 coords for the axes should be enough and I've to mark these points anyways ...

**Comment by nbehrnd** [comment]
@phhoef So far, the approach "one interface in common for multiple cameras/lenses" was known to me only for "true (i.e., non-cellular phone) cameras" (e.g., [magic lantern](https://www.magiclantern.fm/), [chdk](https://chdk.fandom.com/wiki/CHDK)).  By brief consultation of [photo.se](https://photo.stackexchange.com/), the dedicated tag [distortion](https://photo.stackexchange.com/questions/tagged/distortion) however yields one [thread](https://photo.stackexchange.com/questions/131796/imagemagick-distort-values-for-gopro-hero3-black-lens-correction) tapping into the use of [imagemagick](https://imagemagick.org/) and an open access database [Lensfun](https://lensfun.github.io/lenslist/2022/02/22/Lenslist-0.3.3/) for corrections.  Among the entries there are a couple I associate *by name* with cellular phones, e.g. Samsung Galaxy S7.  Perhaps there already is a matching entry to reduce some your work ahead.

Though I'm not too surprised one of the many functions of imagemagick are used, I have no experience with the workflow the lensfun project suggests.

**Comment by phhoef** [comment]
Thanks for your input.
I am currently using Affinity Photo to correct the distortion. I think it will be always an action, that is hard to automate. I was just thinking if I could ease the process as the x1,x2 and y1,y2 points I always need to place could be enough for a semi-automation. A coordinate system is shown on the pic, that's pretty handy to find right-angled lines in the pics ...

To summarize: It's not possible to do a image processing within WPD scripts, right?

**Comment by nbehrnd** [comment]
Affirmative, I do not think WPD is a tool suitable for this because its focus are the data *on top* of a canvas.

Instead, an (eventually) script based approach (e.g., imagemagick, as in its [tutoriel](https://imagemagick.org/Usage/distorts/#perspective) and brief outline on [stackoverflow](https://stackoverflow.com/questions/12276098/understanding-perspective-projection-distortion-imagemagick)) is much more likely to be a reproducible documentation of what was done (and share), and ease to scale on a stack of illustrations of same source.  Or an other library in a language you are familiar with with enough efficiency.

**Comment by phhoef** [comment]
Thank you very much for your thoughts. 
i will have a look if I can easily use imagiemagick, but I think it’s not worth the work. The implementation probably will not be better than the one from affinity photo or adobe Photoshop and is still not integrated in WPD. So the workflow will always be based on two different applications.
