### ISSUE TITLE
Failing to load in mozilla/firefox

### ISSUE THREAD

**Issue by EricPgh** [ankitrohatgi/WebPlotDigitizer#315]
I have the master branch from today and I'm attempting to call index.html within rocky linux in the firefox browser. It has 115.4ESR release from Oct 2023. When I load it, it errors with:
Loading application, please wait...

Problems loading? Make sure you have a recent version of Google Chrome, Firefox, Safari or Microsoft Edge installed. 

When I look at the console for errors/warnings I see:
 1706811526784	addons.xpi	WARN	Checking /usr/lib64/firefox/distribution/extensions for addons
NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1609
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1717
    BG_observe resource:///modules/BrowserGlue.sys.mjs:962
    _delayedStartup chrome://browser/content/browser.js:2051
BrowserGlue.sys.mjs:1618:15
Loading failed for the <script> with source \u201cfile:///home/xxxxxxxx/WebPlotDigitizer/app/wpd.min.js\u201d. index.html:39:25
Loading failed for the <script> with source \u201cfile:///home/xxxxxxxx/WebPlotDigitizer/app/node_modules/pdfjs-dist/build/pdf.js\u201d. index.html:43:55
Uncaught ReferenceError: pdfjsLib is not defined
    <anonymous> file:///home/xxxxxxxx/WebPlotDigitizer/app/index.html:45
index.html:45:9
Loading failed for the <script> with source \u201cfile:///home/xxxxxxxx/WebPlotDigitizer/app/node_modules/tarballjs/tarball.js\u201d. index.html:47:52
TypeError: a is null
    _filterStatic resource://gre/modules/components-utils/mozjexl.js:1
RemoteSettingsExperimentLoader.sys.mjs:541:15

The wpd/app folder contains the following:
build_js.sh            favicon.ico       locale              start.png
build_node_module.sh   format.sh         offline.de_DE.html  styles.css
build.sh               images            offline.fr_FR.html  templates
build_translations.sh  index.de_DE.html  offline.html        tests
combined.js            index.fr_FR.html  offline.ja.html     widgets.css
dev.de_DE.html         index.html        offline.ru.html     wpd-4.7
dev.fr_FR.html         index.ja.html     offline.zh_CN.html  wpd-4.7.tar.gz
dev.html               index.ru.html     package.json        wpd_node.js
dev.ja.html            index.zh_CN.html  README.md
dev.ru.html            javascript        release_notes.txt
dev.zh_CN.html         karma.conf.js     renderHTML.py

The dev.html does load in a limited capacity. The offline.html does the same as index.html.

**Comment by ankitrohatgi** [comment]
Hi, looks like you are missing a few dependencies. Did you take a look at the steps documented here?
https://github.com/ankitrohatgi/WebPlotDigitizer/blob/master/DEVELOPER_GUIDELINES.md#building-source

**Comment by EricPgh** [comment]
I did see those steps while I was troubleshooting. Problem is this system doesn't have npm, and I don't have sudo privileges, so I was in a box.

**Comment by ankitrohatgi** [comment]
The build scripts require a few tools to be installed. Not sure if I can help much here :(
