### ISSUE TITLE
Mismatching versions of website and GitHub release

### ISSUE THREAD

**Issue by udicaprio** [ankitrohatgi/WebPlotDigitizer#316]
Hello everyone,

Thank you very much for your effort in making this tool available.
I noticed that on the web interface, when clicking on Help>About WebPlotDigitizer the version reported is the 4.7, but on the GitHub webpage says that the latest release is the 4.6. 
Is this expected?

Regards,
Ulderico

**Comment by ankitrohatgi** [comment]
Hi, yes - great observation!

There was [an annoying bug](https://github.com/ankitrohatgi/WebPlotDigitizer/issues/303) that I wanted to get a fix out for sooner and it's infinitely much easier to update the website. I am working on desktop versions / official release.
