### ISSUE TITLE
Data not being updated (Blob Detector)

### ISSUE THREAD

**Issue by kartham** [ankitrohatgi/WebPlotDigitizer#39]
There seems to be a problem with the combination of automatic and manual mode. After the automatic mode has applied and I switch to manual mode, I can adjust the points. However, once I try to add points, the red dots are drawn correctly but the points are somehow not registered. Any adjustment of previous points is not registered at all. The point data as shown in "View data" seems frozen. Moving points around or adding or deleting point does not seem to have an effect on the data.

**Comment by ankitrohatgi** [comment]
I switch from automatic to manual many times, but have not seen this issue, but it is possible that I have missed some scenario. I will need some more information from you to investigate further:

1) Which automatic extraction algorithm did you use before switching to manual mode?
2) Which browser and operating system were you using?
3) Did you add multiple datasets from the 'Manage Datasets'?

Thank you!
Ankit

**Comment by ankitrohatgi** [comment]
I went ahead and tried out all the algos. I do see this issue with the blob detector algorithm, but none of the others. Is that the one you were working with?

**Comment by kartham** [comment]
1. Blob - it definitely seems to be related to this extraction algorithm
2. Chrome, Windows 7
3. No.

**Comment by ankitrohatgi** [comment]
Thank you, I will look into it.

**Comment by kartham** [comment]
Great, thanks!

**Comment by ahcyip** [comment]
I had the same problem when using blob detector and then manually adjusting.

**Comment by ankitrohatgi** [comment]
Simply adjusting the positions should work, but if you are deleting and adding points, then there's no way for the program to calculate area and moments associated with that point as they come from the extraction algorithm. I can fix this part so that it lets you add point with empty values for area and moment.

I am curious about the types of images you are using this for. I added this because I needed to measure some particle sizes in an image from a multiphase fluid flow experiment. I think very few people use this algorithm so if you can share a few examples, then it would help me design this part a bit better.

Thanks,
Ankit

**Comment by ahcyip** [comment]
your responsiveness is much appreciated! I was trying to get the red points. Unfortunately none of the algos worked well for this type of shape/point.
![rangel2014](https://cloud.githubusercontent.com/assets/5713411/6743265/daff76d2-ce54-11e4-8017-8b2d7bd28236.PNG)

**Comment by ankitrohatgi** [comment]
The symbols between 1980 to 1990 are very difficult to distinguish even for a human. In this case, you will have to resort to using the manual mode completely. 

The blob detection algorithm is more useful for doing area and shape measurements. I will fix the fact that using this algorithm blocks manual editing of data. 

Thanks!

**Comment by ahcyip** [comment]
Yes I ended up using manual mode completely anyway but wanted a head start on point placement.
But is it true that none of your algorithms can handle "X"-shaped points on X-Y plots?

**Comment by ankitrohatgi** [comment]
It is not dependent on shape. For your case, if you want the 'X' points between 1995 and 2005, then you can even use the default "Averaging Window" algorithm. You will have to raise the delta_x and delta_y values to about 25. For the other overlapping points, it will be hard for the algorithm to calculate the correct centers of the overlapping "X"s.

**Comment by ahcyip** [comment]
makes sense. I guess overlapping points are just quite tricky. thanks.

**Comment by kartham** [comment]
I use the algorithm to catch the centre of circles shown below.

![image](https://cloud.githubusercontent.com/assets/11211715/6747100/69dcbef8-ced4-11e4-9dd1-a5c984b2dca1.png)

**Comment by ankitrohatgi** [comment]
@kartham For your image, you can also use the default averaging window for the points on the right. You will have to do a manual adjustment after this (see image):

![wpd](https://cloud.githubusercontent.com/assets/415640/6765411/5e0892da-cfad-11e4-8df9-685e5b415d71.jpg)

**Comment by ankitrohatgi** [comment]
I have corrected the issue with the blob detector blocking the manual editing btw - I will be included in the next release. Thank you both for pointing it out :)

**Comment by ankitrohatgi** [comment]
delta_x and delta_y of 28 work the best actually: 

![image](https://cloud.githubusercontent.com/assets/415640/6765418/9f8bbeb2-cfad-11e4-8baa-aa700e814a49.png)
