### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by sboeser** [ankitrohatgi/WebPlotDigitizer#40]
Currently, the extracted data can only be exported in .CSV format. This is great for many tools, but e.g. for import in a python script the JSON format is (imho) more convenient. There already exists an "Export to JSON" which stores that data points in pixel units (as well as the axes system befined by the user), but this requires the user to run the coordination transform himself.

I'll happily donate again once this feature is included.

**Comment by ankitrohatgi** [comment]
Hello Sebastian,

I didn't know if anyone was interested I this so I didn't worry too much about this. Since you have showed interested, I will add this part. This should be pretty easy to add.

Also, thank you for the donation!

Cheers,
Ankit

**Comment by ankitrohatgi** [comment]
Sorry about the typos, I'm just trying out the phone app while traveling.

**Comment by sboeser** [comment]
Dear Ankit,

thanks! That would be great. While we are at it - I think it would be also cool if

- there was a way to name the data file (so that they are not all data.csv or data.json and I have to rename them to remember what is what)
- for the JSON export: if this would have all datasets in one file, e.g as a JSON dictionary: { datasetname : data,…}

Cheers and thanks a bunch for this great work,
Sebastian 

> On 27.02.2015, at 12:54, Ankit Rohatgi <notifications@github.com> wrote:
> 
> Hello Sebastian,
> 
> I didn't know if anyone was interested I this so I didn't worry too much about this. Since you have showed interested, I will add this part. This should be pretty easy to add.
> 
> Also, thank you for the donation!
> 
> Cheers,
> Ankit
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-----------------------------------------------

Sebastian Böser

Institut für Physik
Universität Mainz
Tel.: +49 6131 39 23865
sboeser@uni-mainz.de

**Comment by ankitrohatgi** [comment]
I was thinking of just extending the existing JSON export to include the transformed data points.

It is a little trickier to allow the users to rename the downloaded file as there are some limitations with the HTML5 APIs. I will try to see if anything can be done about that.

**Comment by ankitrohatgi** [comment]
This will be available in the next release (next week or so). The exported JSON file will contain the actual values along with the pixels:

Until now, I had
x_pixel = wpd.dataSeries[datasetIndex].data[dataPointIndex].x
y_pixel = wpd.dataSeries[datasetIndex].data[dataPointIndex].y

where datasetIndex is the index of the dataset (e.g. 0 for first dataset). dataPointIndex is the index for the data point in this dataset.

Now the values are also available as
(for example for XY plot)
x_value = wpd.dataSeries[datasetIndex].data[dataPointIndex].value[0]
y_value = wpd.dataSeries[datasetIndex].data[dataPointIndex].value[1]

For a ternary plot, value[2] will contain the third number.

I know this isn't the most efficient way to store the information in the JSON file, but this should work for now. We can revisit this format at a later date if needed.

**Comment by ankitrohatgi** [comment]
Hello Sebastian,

I was doing an analysis on some data, and in the process, I started writing some Python code to work with the JSON file generated from WPD. I have shared the initial attempt on GitHub now: https://github.com/ankitrohatgi/wpd-python

As I was doing this, I remembered that you were doing something similar. Can you share anything from your experience that would be useful to add to this code? I was thinking that perhaps I can even include some common analysis functions (e.g. merge two datasets, interpolation etc.)

Thanks,
Ankit

**Comment by sboeser** [comment]
Dear Ankit,

I think the most useful thing would be just a list of value tuples. The python code is easy enough though that I’m not quite sure we’d need a specific tool for that.

Cheers,
Sebastian

> On 25.04.2015, at 15:48, Ankit Rohatgi <notifications@github.com> wrote:
> 
> Hello Sebastian,
> 
> I was doing an analysis on some data, and in the process, I started writing some Python code to work with the JSON file generated from WPD. I have shared the initial attempt on GitHub now: https://github.com/ankitrohatgi/wpd-python
> 
> As I was doing this, I remembered that you were doing something similar. Can you share anything from your experience that would be useful to add to this code? I was thinking that perhaps I can even include some common analysis functions (e.g. merge two datasets, interpolation etc.)
> 
> Thanks,
> Ankit
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-----------------------------------------------

Sebastian Böser

Institut für Physik
Universität Mainz
Tel.: +49 6131 39 23865
sboeser@uni-mainz.de
