### ISSUE TITLE
Scaling not working

### ISSUE THREAD

**Issue by SimonMcMullan** [ankitrohatgi/WebPlotDigitizer#42]
Hi
Great app - I love it.
I've used it successfully recently without any issues whatsoever for analysing microscopy data with a scale bar. However, I tried to do some analysis today and met a problem I had not previously encountered: I was able to upload an image without incident, but was unable to configure the scale bar appropriately.

I get the usual list of options from the calibrate axes dialogue, but only the 2d plot works (i.e. you get the instructional pop-up and then can enter references for the x and y axes). None of the other options are associated with a pop-up or any actions: you go 'map with scale bar' and click 'align axes' in the dialogue and the window closes but then nothing happens; no pop-up, no actions on click.

I've tried on two different computers (both Win7), tried clearing my cache, and also with the downloadable version, with a variety of different images (including the default sine wave), all with the same problem. I've also tried the polar and ternary calibration approaches; they seem to be dyfunctional too.

Sorry to be a pain - I hope it's something stupid that I'm doing rather than a problem with the app. Thanks for any help.

Simon

**Comment by ankitrohatgi** [comment]
Hi Simon,

Sorry about this! Looks like something was missed in the last update. Thank you for pointing it out. This will be fixed in a couple of minutes.

Regards,
Ankit

**Comment by ankitrohatgi** [comment]
The downloadable version has been fixed too. 

This sort of problem rarely happens as I tend to be careful with the updates. I goofed up this time.

**Comment by SimonMcMullan** [comment]
Hi Ankit

That's awesome - glad it wasn't just me.

I love the tool - it's really made a large impact on our work - thanks 
for coming up with it, maintaining it and, most of all, making it free 
to use.

All the best
Simon

**Comment by ankitrohatgi** [comment]
Most people just use the 2D XY plot and so I am guessing that a lot of people didn't notice it. Also very few people take the time to test and report problems like you did. This sort of feedback is very helpful and if you see issues in the future, then feel free to post them.

Regards,
Ankit
