### ISSUE TITLE
Problem while loading image

### ISSUE THREAD

**Issue by luc-andrea** [ankitrohatgi/WebPlotDigitizer#43]
When I try to load an image I got stuck in "Processing..." and no image is loaded.
My chrome is up to date and it was perfectly working a month ago. Same thing happen on my mac with chrome or safari..
Thanks you in advance and thanks for your very usefull app!

**Comment by luc-andrea** [comment]
My bad.... I just realize that I tried to upload a pdf file.. Sorry

**Comment by ankitrohatgi** [comment]
I'm glad you figured it out. Some day, I hope, dropping PDFs will work too. But I can't see that working on a web-based platform anytime soon.
