### ISSUE TITLE
Throw an error when an invalid file is loaded by accident (Ori: unable to download image)

### ISSUE THREAD

**Issue by mfparadis** [ankitrohatgi/WebPlotDigitizer#48]
I am unable to download an image to WebPlotDigitizer wether I'm trying to download the image, drag it or use cut and paste. Could you please let me know what could be causing this problem? Thank you

**Comment by ankitrohatgi** [comment]
Are you trying to load an image into WPD or are you trying to save the image that you see in the app?

Also which browser and OS are you using?

**Comment by mfparadis** [comment]
I'm trying to load an image into WPD and I'm using Google Chrome and I have a Mac OS X 10.6.8 (I know I haven't done my updates). I have also tried doing the same thing on a PC at the university library using Google Chrome, Firefox and Explorer without success. I've even tried downloading the program itself on a PC and still it didn't work. It keeps saying "processing..."

**Comment by ankitrohatgi** [comment]
What type of image are you trying to load? How large is it? It's not a direct PDF is it?
The app should work fine for images like jpg, png, gif etc.

**Comment by ankitrohatgi** [comment]
If using a valid image file is working for you, then let me know. Since this caused some inconvenience to you, it might be a good idea for me to add an error message whenever someone tried to load an invalid file.

**Comment by ankitrohatgi** [comment]
Assuming that you were loading an invalid image file into the app, I have modified this bug report also in the next version, the software will throw an error message if someone loads an invalid file by accident. It shouldn't be stuck at "Processing" with no information. Sorry about the inconvenience.

**Comment by mfparadis** [comment]
Thank you for your help. I was effectively trying to download an invalid file. I transformed my graphics in jpg and it is working fine. The message you are adding should help to clarify the problem.
