### ISSUE TITLE
Bar Chart Enhancements

### ISSUE THREAD

**Issue by wsloand** [ankitrohatgi/WebPlotDigitizer#51]
I love the way that you've added bar charts (as described in issue #20).

How difficult it would be to add two other features:
1. grouped bar charts?
2. bar charts with error bars?

The problems that I envision are:
For grouped bars especially, I would typically want the categorical value to come with the continuous one.

For error bars, it seems like we could just have 1 to 3 values per bar instead of just one value per bar.  (A work-around for this is just to run it multiple times first choosing the upper bound for the error bar, then the point estimate, then the lower bound.)

**Comment by ankitrohatgi** [comment]
Yes, these would be good future additions. You can add multiple datasets for error bars, but it is a little awkward, I agree. I have tagged this for a future enhancement item.

Thanks!

**Comment by billdenney** [comment]
If #71 and #142 were implemented, I think that they would resolve this issue.

**Comment by billdenney** [comment]
This has been implemented as part of the new point group feature.
