### ISSUE TITLE
Eliminate PHP

### ISSUE THREAD

**Issue by KOLANICH** [ankitrohatgi/WebPlotDigitizer#55]
I looked the source and realized that you don't need PHP.  If you want user to be able to download files, use HTML 5 `download` attribute. remotelauncher.php is also unneeded:.

**Comment by ankitrohatgi** [comment]
This does not work in every browser (e.g. Safari). Also, I remember not being able to control file names with some browsers.

If newer versions of some browsers have added support for this, then I still can't remove PHP as many users are using outdated browsers.

**Comment by KOLANICH** [comment]
If something standardized doesn't work in something which must comply with standard (for example a browser) it is a sole responsibility of the developer of the thing which doesn't comply with the standard. If you allow your tool support obsolete browser, you allow that browser stay obsolete. It is like negotiations with blackmailers: if your position is not hard enough, you will be blackmailed again and again.

2 You should provide a replacement for the ones who have the browsers which are not obsolete and tell the users of obsolete browsers that their data are sent to the server and can be collected there, because they have no mean to make sure they are not.

**Comment by ankitrohatgi** [comment]
I did not have the PHP backend for 2-3 years in the beginning, but it was added later as the objective of this tool is to make life easier for scientists, engineers etc. and not protest against major browser vendors. It was just one of the many pragmatic decisions I made while putting together this tool.

The download attribute does not work to my satisfaction in Safari and even Firefox (maybe this has changed recently) and this is why PHP is needed. Both browsers are extremely popular and even I prefer to use Safari or FF on my own Mac. IE5, 6 etc. are no longer among the top browsers in use. Also, image processing in PHP scripts with a traffic of almost 2000 unique visitors per day is not feasible without an expensive hosting solution.

I can think about adding a replacement for the browsers it does work with, but I don't think it is very critical.

**Comment by ankitrohatgi** [comment]
The other problem was the data size limit. I will have to dig out the numbers again, but the size of data I can pack into the href is very restrictive for some browsers.

I am reopening this request as a future enhancement. Maybe some day we can do this.

**Comment by ankitrohatgi** [comment]
This issue has been addressed now. Thanks to @JakeOShannessy
