### ISSUE TITLE
Ternary Plot doesn't port to plot.ly

### ISSUE THREAD

**Issue by SELindberg** [ankitrohatgi/WebPlotDigitizer#57]
The ternary digitization is an awesome capability.  It does not port into plot.ly though, which is needed for some scientific research.  That capability seems to be missing currently from plot.ly.  I'd like to fix that, and just placed a request in the plot.ly forum.  In any event, I have some funding to sponsor that work in the event you can help.  Ideas?

**Comment by ankitrohatgi** [comment]
Thank you for your offer to help. I have a good working relationship with Plotly, but have never directly contributed to their code. If you get a response from someone in team, then please let me know. I would like to wait for their response before going further. If your request gets buried in their forum, then I can contact someone in their team directly.

Once Plotly supports ternary diagrams, changes in WebPlotDigitizer should be very straightforward and I would be happy to make it work.

**Comment by SELindberg** [comment]
Thanks for the great/quick feedback.  I'll give the Plotly forum some more time and reconnect as appropriate.  Kind regards.

**Comment by SELindberg** [comment]
Wanted to reconnect to let you know that we began communications with Plot-ly, and via this Spring we expect them to have a Ternary chart type as part of their standard list.

**Comment by ankitrohatgi** [comment]
Thanks for the update. Once they expose ternary diagrams to their public API, I can start using it during the export.

**Comment by SELindberg** [comment]
Ankit, FYI, note that our collaboration with Plot.ly has been going very well.  They are nearly done implementing the ternary graphing as part of their many flavors of tools; to be in Plot.ly 2.0 soon (by May 2016).

**Comment by ankitrohatgi** [comment]
Sounds good, thanks for the update!
