### ISSUE TITLE
Averaging window with log scale axis has undesired behavior

### ISSUE THREAD

**Issue by themiurgo** [ankitrohatgi/WebPlotDigitizer#58]
When I tried to get data from a semilogy plot the averaging window method tried to follow the log average, that is, which means that the point was slightly below the average.

I'm not sure that is desired behaviour and at least it wasn't in my case. I ended up getting the data as linear plot and exponentiated it later.

**Comment by ankitrohatgi** [comment]
The averaging window algorithm averages over image pixels and doesn't do a log average. If the mask and color settings are appropriate, then the detected points should be in the middle of the data point or the width of the curve. If that is not what you're seeing, then can you share a sample image?
