### ISSUE TITLE
dense bar charts: negative values not digitized 

### ISSUE THREAD

**Issue by Siesh1oo** [ankitrohatgi/WebPlotDigitizer#61]
First of all: Thank you for the wonderful tool, it is working great for a wide variety of datasets!

However, there is an issue with dense bar charts containing negative values.

Example dataset: http://cdn.get-digital-help.com/wp-content/uploads/2015/08/column-chart-containing-negative-values.png

To digitize, for some reason the "normal" X-Y-plot type works better than the bar-chart-mode. (Labeled bars are harder to convert to dates than ascending fractional X-coordinates, where the fractional part can simply be multiplied by 12 to get the month, and truncated for the year).

However, negative values are not recognized at all (the "uppermost" point of the bar is digitized, so that all negative values are clamped to zero).

Once again: Thank you for the wonderful tool, really great work!

Screenshot of example digitizer session:

![bildschirmfoto 2016-03-09 um 09 54 09](https://cloud.githubusercontent.com/assets/6906374/13629983/f97d9dc8-e5dc-11e5-8341-d33042f5ade1.png)

**Comment by ankitrohatgi** [comment]
XY Axis + Histogram is the correct way to approach this. The fact that negative values aren't picked up needs to be fixed. Thanks for reporting this issue.

**Comment by ankitrohatgi** [comment]
This will be fixed in the next release.
