### ISSUE TITLE
Automatic curve finding fails with transparent image

### ISSUE THREAD

**Issue by wjg3** [ankitrohatgi/WebPlotDigitizer#64]
Title self explanatory. When digitizing an image with a transparent background, the app treats the entire mask as the curve, e.g. filling the entire rectangle. Saving the image with a white background is a workaround, but it would be nice if the app worked natively with transparent images.

**Comment by ankitrohatgi** [comment]
Hi Will, this is a known issue (#44) that I haven't gotten around to fixing yet. Thanks for reporting it though. It helps me prioritize the work.

**Comment by ankitrohatgi** [comment]
I have fixed the issue - it should be available in the next version of the software.
