### ISSUE TITLE
Downloading data to Excel

### ISSUE THREAD

**Issue by manar2010** [ankitrohatgi/WebPlotDigitizer#65]
Hi,
when I try to view the data tin Excel, I get an error message (there is an error sending the data to the program). Any idea what could cause that error. 

Thanks

**Comment by ankitrohatgi** [comment]
Do you mean you get an error when you click "Download .CSV" button?

**Comment by manar2010** [comment]
Yes. It tries to open it in Excel but then I get the error message. I didn't have that problem before and everything was fine until recently. 

Thanks
 

    On Monday, June 6, 2016 12:12 PM, Ankit Rohatgi <notifications@github.com> wrote:
 

 Do you mean you get an error when you click "Download .CSV" button?—

**Comment by ankitrohatgi** [comment]
This is an issue with your browser and Excel settings or installation. There's nothing I can do in WebPlotDigitizer to address your problem. Also, in future, when you see an error message, please report the actual message along with the bug report.
