### ISSUE TITLE
Read image from system clipboard

### ISSUE THREAD

**Issue by jat255** [ankitrohatgi/WebPlotDigitizer#66]
This would be a small enhancement, but a useful one, I think. Many screen capturing software packages (I'm using spectacle on KDE) have an option to simply copy the captured image to the clipboard, instead of saving it to a file. Having an option to read from the clipboard could eliminate a step in situations like this.

**Comment by jat255** [comment]
You know, I never even tried... It does indeed work on Chrome in KDE. 

Perhaps this functionality could be made more obvious somehow on the opening page? That might help inform oblivious users like myself!

**Comment by ankitrohatgi** [comment]
Seems to be working fine for most browsers.
