### ISSUE TITLE
problem with log scale y-axis and decimals

### ISSUE THREAD

**Issue by mt19937** [ankitrohatgi/WebPlotDigitizer#67]
I think there's a problem with the data output when dealing with log scales on the y-axis. I'm setting a calibration point at 10^-3, and telling it to do 1e-3, as per the instructions, but in the data output, it's interpreting it as 1e-4, or off by an order of magnitude.  Even when I use 0.001 as the calibration, it's off. I had to finally adjust the calibration to 0.01 in order to get it to save the data on the scale 0.001.

**Comment by ankitrohatgi** [comment]
I don't see this problem. Which axes type are you using, and which browser? Also just double check if you entering the Y values in the correct order. If possible, can you share the plot (here or privately via email)?

Thanks!

**Comment by mt19937** [comment]
Using Chrome, I'll attach the plot. 

![capture3](https://cloud.githubusercontent.com/assets/20584079/17033908/2df6934a-4f35-11e6-90e0-8a3a4055ea1b.PNG)

I set the calibration at 10^-3 and 10^0 on the y axis, then did the points in succession along the x-axis. When I export as CSV, the y-axis points are off by a factor of 10.

**Comment by ankitrohatgi** [comment]
This is working perfectly fine for me when I enter Y1 = 1e-3, and Y2 = 1 (which is 10^0). I even tried switching Y1 and Y2. The live data under the zoomed area and the CSV data all look good. Are you sure you entered the 10^0 correctly?

**Comment by ankitrohatgi** [comment]
If you are entering everything correctly, then can you do a "Export JSON" from the File menu and send me that file? It will help be diagnose what's going on.

**Comment by mt19937** [comment]
I'm fairly certain I'm doing this correctly. I'm attaching an image of what I'm using for the axes calibration, as well as the plotted excel data from what I'm getting

![capture3](https://cloud.githubusercontent.com/assets/20584079/17034995/00b3680e-4f3a-11e6-920e-38542ba0e22f.PNG)

![capture4](https://cloud.githubusercontent.com/assets/20584079/17034996/00b40994-4f3a-11e6-81c4-8fa47cb89b68.PNG)

 I'll export JSON now

**Comment by mt19937** [comment]
Ah, I just realized my error! Sorry about that. Derp.

**Comment by ankitrohatgi** [comment]
No problem :D I'll close out this issue.

**Comment by mt19937** [comment]
Thanks. Great app by the way!

**Comment by ankitrohatgi** [comment]
Thanks!
