### ISSUE TITLE
Feature Request: Make Dataset Show Full Dataset Name on MouseOver

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#70]
When working with some long dataset names (as an example, "210 mg SAD mean x,+1SEM y"), I can't see the full name of the dataset in the dataset box while entering the data.  It would be helpful if the dataset name showed with a mouseover (by adding the html "title" attribute to the selector).

**Comment by ankitrohatgi** [comment]
This should be easy. I'll get this in soon.

**Comment by ankitrohatgi** [comment]
This will no longer be an issue in the redesigned UI for version 4.0
