### ISSUE TITLE
Feature Request: Multi-level DataSet Names

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#71]
As described in #70, I'm working with multi-level dataset names like: "210 mg SAD mean x,+1SEM y".  In general, the figure I'm working with has data for different dose levels (like "0 mg" and "210 mg"), different treatments (single or multiple ascending dose, "SAD" or "MAD"), and different error measurements for the x and y values ("mean x", "-1SEM x", and "+1SEM x" and "mean y", "-1SEM y", and "+1SEM y").

It would be helpful if I could generate the groups using each of the levels rather than having to type them all in manually.  I find that multiple datasets that are grouped similarly to what I describe above is relatively common in data I'm entering.  The UI I'm thinking of is:
- Menu: Data/Manage Datasets
- Tabs at the top: Ungrouped Datasets / Grouped Datasets (defaulting to Ungrouped)
- If in Ungrouped Datasets, work as the current version works.
  - If in Ungrouped Datasets after using Grouped Datasets, have all the dataset combinations listed separated by the separator character (see below).  This would be the only way to see the number of data points in a dataset.
- If in Grouped Datasets, have two levels of interaction: add/remove group, add/remove level
  - Add/remove group would add (or remove) a group (e.g. "dose levels", "treatment", and "error measurement" from the example above).
  - The group would have a name as a text input box.
  - Add/remove level would add a level within a group (e.g. "0 mg" and "210 mg" for the "dose levels" group).
  - There would be a checkbox to "Use grouped dataset user interface".
  - There would be a single-character input for "Separator character".  The separator character would be used to build dataset names for output with the current formatting (concatenate the group names with the separator character between each level).  A warning would be given if the separator character is used in any level name.
- While entering data, where the dataset pulldown currently is shown.
  - If "Use grouped dataset user interface" is not checked, the current interface is used (using the separator character concatenated dataset names).
  - If "Use grouped dataset user interface" is checked, multiple pull-downs would be given showing the group name to the left of the pull-down and the level as the values of the pull-down.

In the JSON output, there would be a few changes:
- The "name" would be built as currently done for datasets.
- A new element "nameList" would be added that would have the groups in order for each dataset.
- A new element "datasetGroups" would be added that would have the group names (so that the nameList could be mapped back to named groups).

**Comment by billdenney** [comment]
I recently had some more thoughts about this, and I wonder if it may be possible to have a simplified intermediate version of this feature that would support extracting error bar output.

Using a figure like that provided in #74, I'd like to have a single x value with multiple, grouped values on the y-axis representing for example the mean, +1 standard error, and -1 standard error.  The UI that I'd envision is that when adding a new dataset, you could indicate the number of points within one dataset group.  The default would be 1 (which would then work just like the current version).  Then, in the output, an additional column would be added: x, y, group_number.  And, all x-y values within a group would have the same group number.

With that, on extraction, I could work with the data knowing that I have the right points together.

Currently, for a figure like that in #74, I create one dataset for the mean, one for +1 standard error, and one for -1 standard error.  Then after extraction, I have to manually combine the datasets so that I have a single x, with the +1 standard error and the -1 standard error.

**Comment by ankitrohatgi** [comment]
Support for error bars is requested quite frequently, it's among the top few items I'm thinking of working on next.

**Comment by billdenney** [comment]
For the general case, I think that a group of points could be handled instead of a single point.  The point group would then yield wider data than just x- and y- but something like x-group1, y-group1, x-group2, y-group2, etc.

When adding new points, the user would be prompted to enter all of the points simultaneously in sequence by group name, and there would be an option to indicate that a value were missing (I assume represented by a NULL in the x- and y-columns).

To make this really clear with an example:
1. The user indicates that a dataset has a group of points, and gives the point groups names of "mean", "mean +1 standard deviation", and "mean -1 standard deviation".  (Note that the number of points within a group should be unlimited.)
2. When the user is adding a point to the dataset, they would be prompted to add the points in order (e.g. mean then +1 sd then -1 sd in this example).
3. When deleting a point, the user would be asked if they just wanted to delete the current point or the entire point group.  (Something like an alert of "Delete entire point group?" with buttons for "Yes" or "No".)
4. When adjusting a point, it would work as for current points (no group-awareness would be required).

Having it generalized in this way should allow for almost any generalization like + and - error bars in either the x- or y-direction (3 points in the group); + and - error bars in both the x- and y-direction (5 points in the group); bar plots with only + error bars (2 points in the group); and more.

**Comment by billdenney** [comment]
This is covered with the point groups feature.
