### ISSUE TITLE
Feature Request: Ranges as a single value on x- or y-axis (error bar support)

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#74]
I often work with data that has a categorical axis and staggered values on the axis.  As an example, the below image is typical.  Would it be possible to add a feature where the user could select a range of x- or y-points and all the points would be grouped to the same value for that axis?

![image](https://cloud.githubusercontent.com/assets/10359931/17678656/04def846-6306-11e6-8e93-c0e2c6596577.png)

In the example image, they would make the red lines, and as they entered them, they would indicate that anything between the left and right end of the line is 50, 71, 85, 92, 99, 113, 169, or EOS days.  ("EOS" could be required to be a number like 300.)  And, if two lines overlapped, the user would be warned (or even better, the UI would not allow for overlapping lines).

![image](https://cloud.githubusercontent.com/assets/10359931/17678723/567c5a4a-6306-11e6-9d33-30211e601df9.png)

**Comment by ankitrohatgi** [comment]
This should be doable - I never came across such data, so never thought of supporting this :)

**Comment by billdenney** [comment]
This was effectively fixed in #211.
