### ISSUE TITLE
WebPlotDigitizer returns NaN values

### ISSUE THREAD

**Issue by shai-hulud** [ankitrohatgi/WebPlotDigitizer#75]
WebPlotDigitizer returns NaN values for the attached log-scale horizontal bar chart. Plot type is set to 2D bar chart and the axes are calibrated using 0 and 10000 as the two reference points. Log scale is checked. Am I doing something wrong?

![plot](https://cloud.githubusercontent.com/assets/8081876/18268857/eac2547c-7425-11e6-963c-8a64deb9bee1.png
![water consumption 1](https://cloud.githubusercontent.com/assets/8081876/18268870/045787ea-7426-11e6-9a06-ea7d23fb7828.JPG)
)

Thanks for your help!

**Comment by ankitrohatgi** [comment]
I am not able to see the plot, but a log scale axis can never have a "0" value. Are you sure your scale isn't 1 to 10000?

**Comment by Dutch-Piet** [comment]
Hi - the same NaN issue occurred for me when digitizing data from a graph with a logarithmic Y-Axis. I have put the value for Y2 in as "1,000,000,000" resulting in NaN values in the data set.  However, when "tweaking" the XY axis, I then put the Y2 Value in as "1000000000" (i.e. no comma's) and the issue resolved. Hope this helps.
