### ISSUE TITLE
data is being reported as negative on x axis

### ISSUE THREAD

**Issue by ifplumber** [ankitrohatgi/WebPlotDigitizer#76]
on an x-y graph using the program on the web server every graph i make is reporting x axis data with negative numbers even when i dictate that the x axis starts at 0.  it seems that the total number would add up to the x2 number if added together.  
have had this problem on and off for a while.  
I am running it off a mac

any correction or modification needed.

**Comment by ankitrohatgi** [comment]
If you see negative values for some plot, then can you share an image and the JSON output from File->Export JSON?

Also, are you absolutely certain you are specifying the X1 and X2 values in the same order and location as the points that you clicked on the axis?

**Comment by ankitrohatgi** [comment]
Closing the issue until I hear back on this again.
