### ISSUE TITLE
Hysteretic curves

### ISSUE THREAD

**Issue by Qalkaseasbeh** [ankitrohatgi/WebPlotDigitizer#77]
I just found your WebPlotDigitizer, it’s really amazing effort. I’m using this program to extract data from a figure 1 (attached above), and it’s very precise to catch the curve but when I’m taking the extracted data I got different graph (figure 2). Could you help me to solve this? Or at least to separate these curves from each other.

Thanks in advance 
[Figure 1.pdf](https://github.com/ankitrohatgi/WebPlotDigitizer/files/674687/Figure.1.pdf)

**Comment by ankitrohatgi** [comment]
See Issue #62

**Comment by Qalkaseasbeh** [comment]
Nearest neighbor sorting doesn't solve this problem

**Comment by ankitrohatgi** [comment]
That's why #62 is still an open issue :)

**Comment by s1291** [comment]
@ankitrohatgi  both issues are closed.
For an algorithm, see this: https://stackoverflow.com/questions/58377015/counterclockwise-sorting-of-x-y-data
