### ISSUE TITLE
Size of the digitizer points in the zommed window

### ISSUE THREAD

**Issue by FelipeMonts** [ankitrohatgi/WebPlotDigitizer#80]
Ankit Rohatgi,

Great work! I would encourage you to keep working on the R package. It would be a great addition.
I have been having problems with the size of the pointer to digitize data. The zoom window is great, but the size of the pointer and the points already digitized (the red and green points/dots) indicating where the cursor is are very large and hid the data.  This make it difficult to find the precise location of the data point behind the pointer. It would be great to have an option to modify the color and size of the pointer. An alternative can also be to add transparency levels to the pointer fill color, or an option not to have filled color points but only empty or transparent color points.

Thank you!

Keep the great work!

**Comment by ankitrohatgi** [comment]
After some tweaking, I was able to made it a little better (in the code, you'll have to wait for next release to try). Adding user options requires a bit more effort, so I'll keep this open for later.

Cheers,
Ankit

**Comment by FelipeMonts** [comment]
Ankit, 
Thank you for answering my request immediately. 
Wow! I did not expect to hear from you so soon. I am impressed! 
I understand that users options require time. No hurry on my part. 
Take the time you need to make it right and useful! 
Thank you. 


Felipe Montes, PhD 
Production Systems and Modeling 
Plant Science Department 
The Pennsylvania State University 
245 Agricultural Sciences and Industries Building 
University Park, PA 16802 
814 -867- 4612 
frm10@psu.edu 
http://plantscience.psu.edu/directory/frm10

**Comment by ankitrohatgi** [comment]
This is in the latest release. Sorry, it took some time to get the latest version out.

**Comment by FelipeMonts** [comment]
Ankit, 

We used the Web plot digitizer in one of our papers and cited ist use accordingly. 

Here is the paper where we cite your Web plot digitizer. 

Saha, Debasish, Armen R. Kemanian, Benjamin M. Rau, Paul R. Adler, and Felipe Montes. 2017. “Designing Efficient Nitrous Oxide Sampling Strategies in Agroecosystems Using Simulation Models.” Atmospheric Environment 155 (April): 189–98. doi:10.1016/j.atmosenv.2017.01.052. 

http://www.sciencedirect.com/science/article/pii/S1352231017300687 


Fell free to add it to the list of papers that have used your software. 

Thank you. 


Felipe Montes, PhD 
Production Systems and Modeling 
Plant Science Department 
The Pennsylvania State University 
245 Agricultural Sciences and Industries Building 
University Park, PA 16802 
814 -867- 4612 
frm10@psu.edu 
http://plantscience.psu.edu/directory/frm10
