### ISSUE TITLE
Missing Data points in Automatic mode after I pres Run

### ISSUE THREAD

**Issue by adityana** [ankitrohatgi/WebPlotDigitizer#81]
The app was working fine initially.  Now, in the automatic mode, No data points appear when I press run.  The mask option and the filter colour option seem to be working fine. 

The manual option is also working fine.  I can add data points and view corresponding data.  Please help!

**Comment by ankitrohatgi** [comment]
Which algorithm are you using? When you press the "Filter Colors" button, do you see anything highlighted in yellow?

**Comment by adityana** [comment]
The Filter Color option is working fine. I use a pen to draw the area of interest and the plot shows up correctly when I press the Filter color button

The file I was using it on is attached. 
![va_kanai](https://cloud.githubusercontent.com/assets/25515128/22571063/18fb1c8c-e96c-11e6-89f2-114d4a1c0162.jpg)

**Comment by ankitrohatgi** [comment]
**Which algorithm are you using?**

**Comment by adityana** [comment]
Averaging window

**Comment by ankitrohatgi** [comment]
I tried this, and it works fine for me. Did you change the selected color to black?

**Comment by adityana** [comment]
No I hadnt.  I changed it and it works.  Thank you!

**Comment by ankitrohatgi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/415640/22571225/754f042e-e964-11e6-8d25-67a7a4a0414d.png)
