### ISSUE TITLE
Multi-axes support: Set individual x and y-axis values for each dataset.

### ISSUE THREAD

**Issue by Trisk3lion** [ankitrohatgi/WebPlotDigitizer#84]
It would be great if it were possible to set set individual x and y-axis values for each dataset. I have images with several curves but each one with different y-min and y-max.  Right now I have to export the values from each curves in a separate .csv file because when you change the axis the old calculated curve points changes accordingly to the new axis values.
Here is an example picture with current, voltage, resistance and displacement:
![6 1-m](https://cloud.githubusercontent.com/assets/9075125/25337640/ea512c48-28fc-11e7-806d-5d44e02116f6.jpg)

Thanks for all the work, you make my master thesis a lot easier to complete!

**Comment by ankitrohatgi** [comment]
Hello,

Many others have pointed out the need to be able to work with mutiple axes calibrations easily. Your request is very similar. I will try to address this soon.

Thanks,
Ankit

**Comment by ankitrohatgi** [comment]
This has been added now in version 4.0
