### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by MarcWitham** [ankitrohatgi/WebPlotDigitizer#88]
I'm trying to upload a map (jpeg) and the tool is stuck on 'Processing'.  So I'm trying to find out what the issue is.  One thought is that it is too big (3.12MB).  Is that too big?  What other problem sources might be at play?

Thanks

Marc Witham

**Comment by ankitrohatgi** [comment]
What's the image size in pixels (width x height)? There's no limit on file size, but most browsers have a limit on the number of pixels. Also what browser are you using?
