### ISSUE TITLE
Negative Polar Values

### ISSUE THREAD

**Issue by AntennaSolver** [ankitrohatgi/WebPlotDigitizer#89]
I am trying to convert an Antenna pattern diagram.  
The plot is polar, except the radius values need to be both logarithmic and negative.  
Center point is -60 = r.
The next line outwards towards the graphs edge is -50 =r. 
The far outside of the plot is when r = 0.  
Can there be a setting where you adjust the values of the polar diagram? [
![antenna pattern for test](https://cloud.githubusercontent.com/assets/28815471/26267058/2daa0d80-3cb6-11e7-8a3b-4b65d1897512.png)
](url)

**Comment by ankitrohatgi** [comment]
This doesn't look like a simple log scale plot. For log scale plots, the position on the image varies linearly with log of the value. In this case, log(0) or log(-60) doesn't make any sense.

Without knowing this relationship, I can't really help much here. If you discover some relationship, then let me know.

**Comment by galentx** [comment]
I think AntennaSolver is fundamentally looking to digitize a polar plot where some values in the radial dimension are less than zero. So radial_value = pixel_radius*scale - offset. The radial scale is linear in dB, which would make it logarithmic in signal space, but it seems like just accounting for the offset and returning radial values that have units of dB would be sufficient.

**Comment by ankitrohatgi** [comment]
If you look closely at the labels on the radial axis, the radial scale is not linear in dB here.

**Comment by galentx** [comment]
> If you look closely at the labels on the radial axis, the radial scale is not linear in dB here.

Oh, indeed! I had not noticed the nonlinear dB scale. My apologies for adding noise.

**Comment by ankitrohatgi** [comment]
Closing out due to inactivity.
