### ISSUE TITLE
Counting Data Points

### ISSUE THREAD

**Issue by Vicente451** [ankitrohatgi/WebPlotDigitizer#91]
Please consider starting to count data points at 1, rather than 0

**Comment by ankitrohatgi** [comment]
Is this for bar charts?

I don't think adding an option to change this is worth the effort - this is something that you can do after extraction of the data.

**Comment by Vicente451** [comment]
This would apply to all/any chart, and so would not be an ‘option’.

Yes, it is easy to adjust afterwards but why force everybody to do so.

I cannot think of a case where a zero basis is a benefit.

If you take 20 measurements you have 20 data points, 1-20; this is the way most people will

naturally think and requires no explanation.

This is obviously not a biggie but it I think it would polish up your already very nice program.

Vince

**Comment by ankitrohatgi** [comment]
To you 1-20 might seem natural, but to a data scientist writing code, it might not. I'm not sure if this trivial stuff is worth adding extra work.
