### ISSUE TITLE
X-axis misalignment error

### ISSUE THREAD

**Issue by MarillionFan** [ankitrohatgi/WebPlotDigitizer#94]
This is a fantastic tool that I've only recently discovered. No more holding up rulers to my computer screen to try and read values off a graph. However, I've just discovered a bug.

After you have aligned the axes, there is an error in the x-readings. With reference to the graph I have attached, the datapoints that I have circled in red give x-readings of 0 whilst those I have circled in blue give x-readings of 0.25. Now I aligned the x-axis at the top of the graph (y=0) so the readings are accurate here. It's when I move the cursor to the bottom of the graph (y=-30) that the error is at its greatest. It's like there's a skew in the x-axis alignment and this can be seen in my data points getting further away from the graph's vertical grid lines the lower down I go (ie, towards y=-30).

I've tried this on a couple of graphs. At first I thought that there might be a bit of rotation in the graph that I pasted into the app, but not only is this one cut-and-pasted directly from Excel so it should be perfectly horizontal, but I don't see this error in the y-readings (or it's just not as big and within the accuracy of my manual mouse clicks).

![image](https://user-images.githubusercontent.com/29731116/27587364-051bd07a-5b3c-11e7-9ebb-80d4d46f1d72.png)

**Comment by MarillionFan** [comment]
To add to my original post, the y-readings are good. I have circled data points at y=0 along the top of the graph and they all fall on the horizontal grid line.

![image](https://user-images.githubusercontent.com/29731116/27587773-8d4fa092-5b3d-11e7-9ae8-3e9131585e98.png)

**Comment by MarillionFan** [comment]
I've seen what the problem is. It's the way you align the axes. When I click the points for X1 and X2, I'm not caring what the y-positions are at this time. Likewise when I'm clicking on my Y1 and Y2 points, I'm not caring about the x-positions. This results in the skewed readouts, as illustrated above.

The first graph shows my calibration points how I normally do them (although not usually this exaggerated). this leads to the massive errors (and yes, the errors now occur in the y data as well as the x data). The second graph shows my calibration points to be in the corners of the graphs, aligning both x and y points simultaneously. This leads to accurate readouts. 

So this is an effective work-around but surely when it's asking for your x-axis point 1 and point 2, where you click on the y-axis shouldn't matter at all. Maybe a better cal routine would be just to provide two clicks: top left of the graph to give you (X1,Y1) and bottom right to give you (X2,Y2), or wherever you choose to click, but the far extremities would lead to a more accurate cal.

![image](https://user-images.githubusercontent.com/29731116/27588174-237f4792-5b3f-11e7-9b14-3ef61f74a678.png)

![image](https://user-images.githubusercontent.com/29731116/27588293-9eae72b2-5b3f-11e7-8d4d-f0f89bf32102.png)

**Comment by ankitrohatgi** [comment]
The language is very clear, "Enter X-values of the two point CLICKED ON THE X-AXIS.. ". I can't really help if you randomly click all over assuming things work like you are thinking.

**Comment by MarillionFan** [comment]
Ah indeed it does say that. I was thinking it would just pick up the X1 and X2 points irrespective of the Y-position since it is only X-values you are defining at this time (likewise when defining Y1 and Y2). I just assumed the equation for scaling the x-axis would involve x-data only. My bad.

Thanks for your reply.
