### ISSUE TITLE
Feature request: Support fractional dates

### ISSUE THREAD

**Issue by galentx** [ankitrohatgi/WebPlotDigitizer#95]
Some plots with a calendar axis actually have data with finer time resolution than one day, but this information is lost when the axis is configured for dates. Generalizing the date format to include time fields (hh:mm:ss and possibly fractional seconds following a decimal point) would solve this limitation. The axis calibration input would also need to allow for this extended format.

**Comment by ankitrohatgi** [comment]
Support for time has been added now. Thanks to Steffen Rehberg (@StefRe)

**Comment by galentx** [comment]
Haven't had a chance to test it yet, but thank you!
