### ISSUE TITLE
Slow CSV download

### ISSUE THREAD

**Issue by Gryllida** [ankitrohatgi/WebPlotDigitizer#97]
Click 'view data', click 'Download .CSV' takes more than 5 seconds.

**Comment by ankitrohatgi** [comment]
Hosting is reaching it's limits as the users increase. I'll look into it this weekend.

**Comment by JakeOShannessy** [comment]
I run patch for this on my own computer by doing everything client-side, but I've noted in other places that the php backend has been retained for backwards compatibility. Is there a particular set of environment this project tests against? because I've only tested against the latest browsers.

**Comment by ankitrohatgi** [comment]
This has been addressed now
