### ISSUE TITLE
Getting edge detected in an image

### ISSUE THREAD

**Issue by samiit** [ankitrohatgi/WebPlotDigitizer#99]
Can I use WPD to get edges in an image? I want to use it to get outline of a vertebra in an X-ray image. Any other suggestion?
Thanks,
Sam

**Comment by ankitrohatgi** [comment]
Hi Sam,

I think if you did the edge detection in some software like GIMP, Photoshop or ImageJ, then you can digitize the outlines in WebPlotDigitizer. Most investigators tend to either write custom code for such cases in Python/Matlab or create an ImageJ plugin. You might want to explore some existing ImageJ plugins for this purpose as well.

Regards,
Ankit

**Comment by samiit** [comment]
Thanks Ankit.
Can you suggest a suitable package in Python?

Regards,
Sam
